### ISSUE TITLE
Starting dev mode fails using latest (Jan 2024) production database backup.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#1068]
**Describe the bug**

Using a copy of the production database fails to boot the database. This error is displayed when dev mode is started

```
$ mvn quarkus:dev -pl '!horreum-integration-tests'
...
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 13.11 (Debian 13.11-1.pgdg120+1).

```

Start dev mode with master branch and using a backup of production database.

**Version**

```
f5e6f73c43b3c10b56ed6456411233d838e3933a
```

**Java**

```
17
```

**PostgreSQL**

What is the version of PostgreSQL ?

```
13
```

 The database version needs to be bump in the configuration that starts dev mode.

**Comment by johnaohara** [comment]
What are you trying to do here? it looks like start an old version of 0.10.x (commit f5e6f73c43b3c10b56ed6456411233d838e3933a) against a recent backup of a prod?

The current 0.10.x branch works against postgres:16 (https://github.com/Hyperfoil/Horreum/blob/0.10.x/pom.xml#L96, but there is no way to make an older version forward compatible with current postgres version used in production.

The only way to make this work is to branch from f5e6f73c43b3c10b56ed6456411233d838e3933a and change the postgres version, but that is not a bug
