### ISSUE TITLE
UI Tags column in Run List missing a value.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#108]
Looking at the run list I see the Tags column is empty.
![missing-tag-column](https://user-images.githubusercontent.com/708428/148984655-81255201-1226-41d5-9963-90d467ac2c23.png)

**Comment by rvansa** [comment]
Hi, unless this is just a remark as you want to fix the issue yourselves the information above is insufficient. Tags can be empty if you don't specify any accessor in test configuration (General tab) or if it doesn't match.

**Comment by whitingjr** [comment]
The accessor values are visible in another column.
For some reason unknown to me this tag column has started showing today.
