### ISSUE TITLE
Generate a Permalink on a run view for a json path expression to allow sharing of snippets of data

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#113]
The current "run" view allows users to dynamically create a json path expression that is evaluated against the json data for that run.

There are times when the content of the json is being discussed that is not part of the regression variable set (e.g. config params).  It would be helpful for discussing the contents of the json object if a permalink was created next to the json expression box (or somewhere that is easy to view/copy) for the run and the json path expression that could be shared.

e.g. a link such as `https://horreum.exmaple.com:8443/run/6008?jsonpath=%24.config.params` would open the run view for #6008 and apply the json path to the data

![Screenshot from 2022-01-28 12-58-39](https://user-images.githubusercontent.com/959822/151551704-c68a7beb-f480-435a-8167-ad43114f53b4.png)

**Comment by rvansa** [comment]
Implemented.
