### ISSUE TITLE
Port backend to RESTEasy Reactive

### ISSUE THREAD

**Issue by geoand** [Hyperfoil/Horreum#116]
[RESTEasy Reactive](https://quarkus.io/guides/resteasy-reactive) is now the preferred REST API in Quarkus (for multiple reasons).

For the `backend` of this repository, unfortunately it's not a matter of simple replacing the dependencies, as RESTEasy Reactive does not use Servlets.

This means that the Servlet Filters need to be migrated to JAX-RS `ContainerRequestFilter` and also the various usages of Servlet types need to be replaced by either generic JAX-RS types or Vert.x types.

**Comment by geoand** [comment]
Makes sense!

**Comment by geoand** [comment]
When you folks do want to make this move, let me and I can help :)

**Comment by johnaohara** [comment]
@geoand thank you very much for the offer :) There a couple of new major features being implemented (#121 & #122) at the moment. It would be worth waiting until these have been implemented before about porting the backend to RESTEasy Reactive. We can ping you when those issues are closed if you would like?

**Comment by geoand** [comment]
Sounds good

**Comment by rvansa** [comment]
@geoand Actually as long as we don't have to reimplement API methods (just flag them as `@Blocking` or something along those lines) you could try to migrate it - I guess the servlet filters will need a rewrite, maybe interceptors.

**Comment by geoand** [comment]
I talked to @johnaohara about this and I'll take this up soon after some tests have been added to the project :)

**Comment by johnaohara** [comment]
@rvansa I confirmed with @geoand that it should be fairly trivial to migrate the stack to RESTEasy Reactive, we need to add some tests to ensure that any changes to the filters don't break behaviour, as they need migrating.  CDI interceptors *should* continue to work as-is

**Comment by johnaohara** [comment]
and RESTEasy Reactive can determine if the method invocation should be run as a blocking call based on the method signature

**Comment by rvansa** [comment]
Done in https://github.com/Hyperfoil/Horreum/pull/229
