### ISSUE TITLE
Add http linking in test run describtion

### ISSUE THREAD

**Issue by dupliaka** [Hyperfoil/Horreum#119]
For example like this
![image](https://user-images.githubusercontent.com/21653197/152876955-9da8ddc8-209b-4194-a901-058c6f364715.png)
Here I have tried to have a 
<a href="https://github.com/kiegroup/optaplanner/commit/1ea1f14fb52563b60af48747e9a24c4e67f32fc3">8.15.0-SNAPSHOT</a>
Usually each run is a stat of some repo so that might be usefull to be jump right at the broken code of the app

**Comment by rvansa** [comment]
Implemented.
