### ISSUE TITLE
reload of data sets  page ends with blank screen

### ISSUE THREAD

**Issue by jhutar** [Hyperfoil/Horreum#1197]
**Describe the bug**
Reload of data sets  page ends with blank screen

* request `/run/dataset/list/assets/index-c8CVUqv3.js` returns 404, Firefox shows `NS_ERROR_CORRUPTED_CONTENT`
* request `/run/dataset/list/assets/index-Lkl1mR35.css` returns 404
* request on `/run/dataset/list/favicon.ico` returns 404 as well

**To Reproduce**
1. Find your test
2. Click the number in "Datasets" column
3. Notice the page looks as expected
4. Reload the page

Getting blank screen now.

**Version**
Current in Prod

**OS**
Fedora release 39 (Thirty Nine)

**Browser**
firefox-121.0.1-1.fc39.x86_64

**Comment by jhutar** [comment]
Recorded it here: https://drive.google.com/file/d/1U-WOzTH-JBATewtS7d69epaRkaDzKb4f/view?usp=sharing

**Comment by johnaohara** [comment]
@jhutar Thank you for the steps to reproduce. I had noticed the same on Friday (https://github.com/Hyperfoil/Horreum/issues/1176)  but did not have steps to reliably reproduce.  This looks it was caused by our move to vite for the UI build tool

**Comment by johnaohara** [comment]
Fxied in https://github.com/Hyperfoil/Horreum/pull/1201
