### ISSUE TITLE
[horreum-api] RunService.add service deserealization problem of io.hyperfoil.tools.horreum.entity.json.Run.class

### ISSUE THREAD

**Issue by dupliaka** [Hyperfoil/Horreum#120]
While using Run class to send RunService.add and sending Instant date the data that client creates does not fit in the module

The json created by sending Run instance: 
```
{
  "owner": null,
  "token": null,
  "access": 0,
  "id": null,
  "start": .
  "nano": 123456789,
  "epochSecond": 1644121187.,
  "stop": .
  "nano": 123456789,
  "epochSecond": 1644121187.,
  "description": "8.16.0-SNAPSHOT a3255b0d1d099987a338bbd61b46dbaea2d5fcfb",
  "testid": 117,
  "data": [
    ...
  ],
  "trashed": false
}

```

The issue

```com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.time.Instant`from Object value (token `JsonToken.START_OBJECT`). at [Source:(io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 57] (through reference chain: io.hyperfoil.tools.horreum.entity.json.Run[&quot;start&quot;])```

**Comment by rvansa** [comment]
I've created a test in 3ca6001d10b51e70dca54d977b76defb27c897e7 and it works; therefore closing this as (probably) outdated.
