### ISSUE TITLE
Replace SchemaExtractors with Labels

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#122]
Note: the term `Label` is subject to discussion. Please edit and put your suggestions for alternatives and votes below:
* Label: (no votes)
* Property: rvansa

Also what is currently called *Tags* should be renamed to `Fingerprint`; alternatives below:
* Fingerprint: rvansa
* Selector: (no votes)
* Identity: (no votes)

* [x] #155
* [x] #162
* ~Labels garbage collection~ Deferred - we don't offer label rename right now.
* [x] #156
* [x] In Test/General, remove Tags and add Fingerprint selection where you can pick one or more Labels. Only labels with 'Suggest for filtering' on will be suggested here. ~Note that we won't move this under Change Detection because the Fingerprint can be used for other purposes, e.g. for filtering Missing runs notification (this probably needs a bit more discussion).~ Missing runs notification uses its own filtering.
* [x] Add optional Fingerprint filtering function to Change Detection: this function will be applied on the fingerprint of each run (object keyed by label names) and if the result is not truthy the Change detection will skip this run. If the function is not defined all Runs are subjects to Change detection.
* [x] #198
* [x] #171
* [x] #170
* [x] #175

All steps involving removal of configuration elements should include a DB migration changeset that will create respective labels.

**Comment by dupliaka** [comment]
idea for term "Label"
Annotation

idea for Fingerprint
Revision

Are Tags in Series going to be replaced by  Fingerprint? How to filter Series of the same tests if you want to compare results form the same branch?

**Comment by rvansa** [comment]
@dupliaka Yes, in this case it's mostly a rename. I've seen people getting confused as they wanted to use Tags here in Horreum with exact versions (as you would use tag in git), to display extra info etc. Here the purpose is only identification of the series.

Annotation could work, though the purpose of Labels is not only extracting metadata (that's what I associate annotations with), but also results (e.g. latency).

Revision would be misleading IMO - I've checked the meaning online and it looks that's is mostly used as micro-version identifier, e.g. build number. Here it's completely the opposite - you should have multiple versions of your product with the same fingerprint, as long as it is used in a consistent configuration.

**Comment by johnaohara** [comment]
Another way of thinking of Tag/Fingerprint, could be to think of the combinations of properties as a "selector", i.e. you are selecting all data items with these properties to run change analysis against
