### ISSUE TITLE
Fecth roles from the DB into the `SecurityIdentity` object

### ISSUE THREAD

**Issue by barreiro** [Hyperfoil/Horreum#1258]
Use a `SecurityAugmentator` like described in https://quarkus.io/guides/security-customization#security-identity-customization

**Comment by barreiro** [comment]
Ideally, these should be the "team roles" for requests that are team scoped.

**Comment by johnaohara** [comment]
@barreiro have any of the recent PR's fxied this issue? or is it still outstanding?
