### ISSUE TITLE
Horreum Elasticsearch Authentication 

### ISSUE THREAD

**Issue by jtaleric** [Hyperfoil/Horreum#1283]
**Feature idea.**

Support user/pass along with API-Key

**Describe the solution you'd like**

Allow Horreum Elasticsearch Integration to supply a User/Pass to read from Elasticsearch

**Additional information**

Attempting to make a read-only API key w/

```json
POST /_security/api_key
{
  "name": "rook-key",
  "role_descriptors": { 
    "role-a": {
      "cluster": ["all"],
      "indices": [
        {
          "names": ["*"],
          "privileges": ["read"]
        }
      ]
    }
  }
}
```
However, I am met with this response `{"Message":"Your request: '/_security/api_key' is not allowed."}`

Looking at AWS-ES documentation it appears an API-Key is not possible. 

`Security API is part of x-pack which is not support yet by AWS Elasticserach service.`

**Comment by johnaohara** [comment]
Fixed in : https://github.com/Hyperfoil/Horreum/pull/1299
