### ISSUE TITLE
Add code completion to build JSON path

### ISSUE THREAD

**Issue by stalep** [Hyperfoil/Horreum#13]

**Comment by rvansa** [comment]
I've added the autocompletion feature to search in Runs; you could use the REST API from anywhere, though. Is this done then?

**Comment by rvansa** [comment]
Added autocompletion to select data from each Run; this uses client-side (javascript) `jsonpath` as opposed to the search over all runs when filtering in AllRuns page that executes the query directly in Postgres; I've added some regexps to handle Postgres-style jsonpath syntax, though Postgres can do queries which are not possible in the JS version, so it's far from 100% compatibility.
