### ISSUE TITLE
Async Label render functions result in incorrect LabelValue

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Horreum#1320]
**Describe the bug**

An async label render function will result in Horreum storing the String representation of the promise as the label value instead of the resolved value of the promise.

**To Reproduce**

Steps to reproduce the behavior.

1. Create a render function with `async (arg)=>arg` and the resulting label value will not be `arg`

**Version**

What is the version of Horreum ? master

**Comment by stalep** [comment]
This should be discussed further as it adds features to Horreum we've not discussed.

**Comment by willr3** [comment]
I disabled the `fetch` support in the PR but left in the global shims for `atob` and `btoa`. Is there more we think we need to edit on the PR before suppport `async` javascript method declaration?

**Comment by willr3** [comment]
I removed the sandbox changes to support IO from javascript and changed the `evaluateOnceAsyncAwaitFetchJson` unit test to ensure Horreum does not run fetch.

**Comment by willr3** [comment]
Do you want updates placed in the issue or the PR's? I removed the code changes that added any support for `fetch` in the PR.
