### ISSUE TITLE
Compare URL Function is not adequately sanboxed

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Horreum#1328]
Currently `test.compareUrl` is treated as a javascript function in the Horreum UI and is executed each time the user changes the row selection. This function executes in the browser. Horreum should not execute user provided javascript in the browser.

Possible solutions:
1. change `compareUrl` to be a `url` and Horreum will pass the selected `runIds` as parameters to the url 
    Pros: 
    * no javascript execution

    Cons:
    * breaks any existing compareUrl in the production DB
2. execute the javascript function on the server sandbox and send the response back to the user
   Pros:
   * no change to existing compareUrl in the production DB

   Cons:
   * requires a new endpoint in the service api
   * introduces a delay to prepare the `Compare Runs` button that must be synchronized client side
3. execute the javascript in a client side sandbox
   Pros:
   * no change to existing compareUrl in the production DB

   Cons:
   * Additional dependency and scoping of supported javascript
   * Security concern for escaping sandbox
   * UI stability concern for escaping sandbox

I vote option 1 and am working on a PR.

**Comment by johnaohara** [comment]
@willr3 is there a way of migrating `breaks any existing compareUrl in the production DB` in changelog.xml?  We can break existing installs without a migration path, or documentation
