### ISSUE TITLE
Synchronize openapi.yaml with current main branch

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1351]
**Describe the bug**

The current openapi.yaml (https://github.com/Hyperfoil/Horreum/blob/master/docs/site/content/en/openapi/openapi.yaml) is out of sync with the actual api defintion

**Comment by johnaohara** [comment]
I noticed this PR that does not have the corresponding openapi.yaml changes: https://github.com/Hyperfoil/Horreum/pull/1337

But there appears to be others that have been merged and not updated the openapi.yaml

**Comment by webbnh** [comment]
I don't want to speak out of turn, but it is a bit strange to expect something which is generated by the build to be committed to the source repo in a PR which, in essence, exists before the build does.

Files produced by the build, whether they are `.jar` files, or generated documentation, or the `openapi.yaml` file should be published from the build results area and not fed back into the source repo.

However, until you decide to pursue that change of model, it seems like it might be an easy test to diff the `openapi.yaml` file produced by the build against the one provided by the repo -- if they differ, then the build (i.e., the PR) should be considered a failure.
