### ISSUE TITLE
Automatic 1:1 transformation of Run into DataSet

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#138]
When a new Run is inserted/updated to the DB it should call pg_notify that will be intercepted in the app and will write one DataSet. Deletes should remove all DataSets for that run (that can happen within DB). #138

**Comment by whitingjr** [comment]
Is it an assumed the App will always be running ? For example running an import of backed-up/dummy data for example will fail to keep DataSet in sync.

**Comment by rvansa** [comment]
That's a valid concern. There should be an API (+button in UI) to perform the transformation for any reason that could desync those.

**Comment by rvansa** [comment]
Btw. if this approach causes trouble in the future we could add an auto-incremented (via trigger) column in Run that will denote the version and a similar column in DataSet; a periodic process could check if the datasets have matching version and recompute them.
