### ISSUE TITLE
Full list of folders not displayed on Changes view

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1402]
**Describe the bug**

The complete list of folders is not being displayed in the Changes view in the current master branch;

Stable;

![Screenshot from 2024-03-04 09-34-44](https://github.com/Hyperfoil/Horreum/assets/959822/213c75ca-75e2-4913-b8ab-7037e6da63cb)

Master;

![Screenshot from 2024-03-04 09-34-36](https://github.com/Hyperfoil/Horreum/assets/959822/58ee3dc8-f083-4feb-b5cb-2dad2c641241)

**Comment by whitingjr** [comment]
Before login you see all Tests.
After logging in the default drop down option is "Only my own".
Are you expecting something else ?
