### ISSUE TITLE
Add functionality to link to privacy statement in the "About" popup

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1408]
**Describe the bug**

To comply with legal requirements, a privacy statement should be made available to end users.  This can change between installations, so the privacy statement should be a configurable URL that can displayed as a link in the about popup

**Comment by lampajr** [comment]
Hey @johnaohara, if I correctly understood this would be about adding new "row" here:
![image](https://github.com/Hyperfoil/Horreum/assets/26715795/6f9026e9-6186-4014-9572-6609167fcb1a)
where we would show the privacy stmt configurable URL.

Here two doubts:
* I still do not have fully clear how you were thinking about its _configurability_ :confused:
  * I was thinking to make the URL configurable through env variables/java props in backend and return it as part of the `VersionInfo` object [1], wdyt?
* Do we already have a default to use? 

[1] https://github.com/Hyperfoil/Horreum/blob/3e54bbc7dcbc0def68bfaa7eb3f679468e6c40e7/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java#L58-L62
