### ISSUE TITLE
Enable RBAC Roles on `api/user/search` endpoint 

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1409]
**Describe the bug**

All users accounts are searchable via `api/user/search` if a user is authenticated

This should be restricted to Administrators

**Comment by whitingjr** [comment]
@johnaohara Does the same RBAC restriction also apply to [UserService.info](https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java#L41-L43) method ?

**Comment by barreiro** [comment]
I don't know if I agree with this issue. If `search` and `info` endpoints are restricted to Administrators then a team manager will not be able to find existing users to add to it's team.

**Comment by whitingjr** [comment]
@johnaohara ^^ any comment ?

**Comment by johnaohara** [comment]
> I don't know if I agree with this issue. If `search` and `info` endpoints are restricted to Administrators then a team manager will not be able to find existing users to add to it's team.

We can not have an unsecured API that anyone can search for user details.

IF we need to add `Managers` to the list of authenticated users, then we need to add managers as well as administrators

**Comment by johnaohara** [comment]
> @johnaohara Does the same RBAC restriction also apply to [UserService.info](https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java#L41-L43) method ?

yes

**Comment by barreiro** [comment]
> We can not have an unsecured API that anyone can search for user details.

At the moment, the API is secured in the sense that it is restricted to *authenticated* users. Do we want to restrict it just to `Managers` ??

**Comment by whitingjr** [comment]
Both Managers and Administrators for both method.

**Comment by johnaohara** [comment]
I opened this particular issue on Mar 5, when the class was annotated with `@PermitAll`. On March 20th a PR (https://github.com/Hyperfoil/Horreum/pull/1525) changed the annotation. 

> I don't know if I agree with this issue.

@barreiro what part of this issue do you not agree with?  That we should not have restricted it, or that is should not be just `Administrators`?

**Comment by barreiro** [comment]
@johnaohara I don't agree that should be just `Administrator`, as team managers need to search for users to add to their teams.

before #1525 the authorization was already being enforced in the methods, that commit just changed authorization to be annotation based which is the way to go IMO.

**Comment by johnaohara** [comment]
Having looked at this again in more detail;

- Access to personal User information should be restricted to the roles that **need** it 
- Horreum is a multi-tenanted system, with multiple teams that are not related.  It is not acceptable that **any** authenticated user can search the personal information of any other instance user (just imagine company A and company B using a shared instance, users in company A should not have access to the usernames and email addresses of all users in company B)

In theory, we need to;
- restrict access to roles that need the information, probably  'Administrators' and 'Managers' (although originally in https://github.com/Hyperfoil/Horreum/blame/ddce7c119dc76a3f2ba9e2a9c9422383dfc3d98f/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java#L47C4-L47C55 the roles `{Roles.VIEWER, Roles.TESTER, Roles.ADMIN}` were allowed - idk why `Viewer` and `Tester` were required)
- restrict access to user information for Managers to users on the teams they manage

However, the 2nd requirement fundamentally challenges the assumptions about the user model Horreum currently uses, i.e. a team `Manager` can search for **all** users in the system - I think this assumption is flawed in a true multi-tenanted system where we can not assume a commonality between tenants.

So, I think we should look at requirement 1) and defer requirement 2) to a discussion about "What multi-tenancy means in Horreum"

**Comment by whitingjr** [comment]
@barreiro the PR implements the 1st requirement and ready for review.

**Comment by whitingjr** [comment]
This has been fixed by #1562
