### ISSUE TITLE
Team managers unable to add new users

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1419]
**Describe the bug**

Team managers were able to create new users and add them to their respective teams. 

Since the change to the security model, adding a new user adds the user to the `userinfo` table, but does not add the user to the keycloak instance. 

As a result, Team managers are no longer able to manage their team without assistance from an administrator

**Comment by johnaohara** [comment]
@barreiro you mentioned this could be fixed by changing the configuration, is that changing `horreum.roles.provider=database` to `horreum.roles.provider=keycloak` ?

**Comment by barreiro** [comment]
@johnaohara do you think having a mixed `UserService` service that adds the user both on keycloak and database makes sense ?

I don't think so and I'll argue that if you need to add the user to keycloak you probably should have the roles in keycloak too and not on the database.

**Comment by johnaohara** [comment]
@barreiro i don't think a mixed mode makes sense. 

The problem I was having was if we perform the migration for a prod system, admins could not add new users (this would be a regression),  but setting the config back to previous was causing this issue - https://github.com/Hyperfoil/Horreum/issues/1445

I think https://github.com/Hyperfoil/Horreum/pull/1450 will fix this issue as well as https://github.com/Hyperfoil/Horreum/issues/1445
