### ISSUE TITLE
package-lock.json incorrectly formatted

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1421]
**Describe the bug**

The current `package-lock.json` file is incorrectly formatted after https://github.com/Hyperfoil/Horreum/pull/1406 was merged.

As per discussion: https://github.com/Hyperfoil/Horreum/discussions/1245 the `packag-lock.json` needs manual fixing by checking out the master branch and running;

```
mvn clean -Premove-node-cache
mvn clean install -DskipTests -DskipITs
```

The resulting `package-lock.json` should be correctly formatted

@whitingjr please can you take a look at this?

**Comment by whitingjr** [comment]
Yes I am looking at this now.
