### ISSUE TITLE
Unable to parse start time

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1484]
Previously working upload have started failing with the following error message:

`Cannot parse start time from 2024-03-13T21:18:10.878423-04:00 ($.start_time)`

Jobs that adhered to this datetime format were previsouly imported, e.g.:

`"start_time": "2024-03-11T22:16:24.302655-04:00"`

This change was likely introduced here: https://github.com/Hyperfoil/Horreum/pull/1322/files#diff-0a2af3ce63d006af3ce2a9893563d8cc63de6e2c648d8b35af1a6c26e7ecb98f

**Comment by willr3** [comment]
Do we want to remove the final pattern match or fix the pattern? I vote remove the pattern match because clearly the ISO format supports more shapes than what was documented in the javadoc

**Comment by johnaohara** [comment]
> Do we want to remove the final pattern match or fix the pattern? I vote remove the pattern match because clearly the ISO format supports more shapes than what was documented in the javadoc

+1 to removing regex
