### ISSUE TITLE
Ignore files/folder from reformat

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#1488]
Use `.prettierignore` to ignore (i.e. not reformat) certain files and folders completely.

check- https://prettier.io/docs/en/ignore

**Comment by johnaohara** [comment]
@shivam-sharma7 what files are we reformatting at the moment? when does this occur?

**Comment by johnaohara** [comment]
> @johnaohara I have added this as mendatory and its a part of configuration with prettier and another reason is lock file is still reformated by dependabot PRs.

@shivam-sharma7 How does this help with the  dependabot PRs?

**Comment by shivam-sharma7** [comment]
@johnaohara TBH I have not tested yet but this will help locally, but I'm not sure about dependabot PRs
