### ISSUE TITLE
add label name filtering to `/labelValues` endpoints

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Horreum#1530]
The `/labelValues` endpoint on `test` and `run` currently return all the labels which can be a prohibitively large amount of data for use cases that only want a few labels. 
It would help if users can specify which labels to include (or exclude) as part of the query API.

Current idea is an `include` and an `exclude` query parameter that accepts label names

**Comment by barreiro** [comment]
```
?include=foo,bar&exclude=other,stuff
```
seems to de the standard way for parameters of list type

**Comment by lampajr** [comment]
> ```
> ?include=foo,bar&exclude=other,stuff
> ```
> seems to de the standard way for parameters of list type

+1 I think that comma separated list is the standard for these use cases

**Comment by willr3** [comment]
it looks like `?include=foo,bar` and `?include=foo&include=bar` work. Learned something today :)

**Comment by willr3** [comment]
I thought comma separated was handled by `jakarta.ws.rs` but I was fooled by my `System.out.println`. `jakarta.ws.rs` will create two list entries from `include=foo&include=bar` but `include=foo,bar` is being treated as a single entry in the list. We could create a custom parsing for it but if `,` separated was the standard I would expect `jakarta.ws` to parse it

**Comment by lampajr** [comment]
I couldn't find any doc but I found a PR mentioning something like that https://github.com/quarkusio/quarkus/pull/29550

**Comment by willr3** [comment]
You're right, there is the `org.jboss.resteasy.reactive.Separator` annotation that adds the ability to specify `include=foo,bar`. It isn't part of the `jakarta.ws` spec but Horreum is a quarkus app not a portable jakartaEE app so I think it is safe to add the dependency. 
I will check how it impacts the openapi.yaml

**Comment by willr3** [comment]
Adding the `Separator` did not change the openapi.yaml so I've added it to the PR. Users can use `include=foo,bar` or the `jakarata.ws` approach `include=foo&include=bar`
