### ISSUE TITLE
Change workflow check to reformate package-lock.json

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#1552]
**Describe the bug**

Dependabot is producing files that reformat the file that conflicts with the teams style rules.

**Version**

What is the version of Horreum ?

```
0.12.0
```

**Comment by johnaohara** [comment]
As mentioned on the PR:

was searching for this issue and came across this  comment: https://github.com/npm/json-parse-even-better-errors/issues/3#issuecomment-1668728929

` Maybe those people complaining about their package-lock not using ... double-spacing just like their package.json file were just a vocal minority, ` 

our package.json is double spaced

We had a brief discussion about trying;
- single spacing out package.json
- fixing the npm version in package.json to ensure dependabot picks the correct version: https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json
- explicitly defining the npm version in https://github.com/Hyperfoil/Horreum/blob/master/.github/dependabot.yml


If we can fix the `package-lock.json` format produced by dependabot, I don't think we need an action to reformat the `package-lock.json`
