### ISSUE TITLE
Delete Team does not cascade delete to the number of Users associated to the Team. Keycloak or Database backends.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#1563]
**Describe the bug**

When deleting a Team the count of UserData objects remains the same after the delete is complete.

**To Reproduce**

Steps to reproduce the behaviour.

tbc.....

This testcase will fail with an error 
```
[ERROR] Failures: 
[ERROR]   DatabaseUserServiceTest>UserServiceAbstractTest.userCountAfterDeleteTeamTest:445 expected: <10> but was: <11>
[ERROR]   KeycloakUserServiceTest>UserServiceAbstractTest.userCountAfterDeleteTeamTest:445 expected: <13> but was: <14>
```

**Version**

```
master 41cd4e526fc0b763ec4f6c37aca64e7e7b4a672c
```

**Comment by barreiro** [comment]
This is expected. We *never* delete users.
When removing a team what we remove is the *association* between a user and the team. The user can become associated with other teams afterwards.
