### ISSUE TITLE
Add Relative baseline to Horreum Report

### ISSUE THREAD

**Issue by dupliaka** [Hyperfoil/Horreum#157]
While comparing performance changes it is much easier to see relative differences bar like it shown here:

[Optaplanner: How much faster is Java 17](https://www.optaplanner.org/blog/2021/09/15/comparison-java11-java16-java17-G1GC.png)

The idea is to add a baseline acessor and give in tables the relative differences in % from the baseline

**Comment by rvansa** [comment]
Implemented in #195
