### ISSUE TITLE
link to the change from email does not work

### ISSUE THREAD

**Issue by jhutar** [Hyperfoil/Horreum#1574]
**Describe the bug**

I got this "change detected" email:

```
Subject: [RHTAP-Perf-Notification] [Horreum] Change in load-tests-result

[-- Autoview using lynx -display_charset=utf-8 -dump '/tmp/neomutt.html' --]
   Hello rhtap-perf-test-team,

   Horreum detected a recent change in test [1]load-tests-result,
   introduced with dataset [2]28328#1.

   These change detection variables observed a change:
     * cluster_network_transmit_bytes_total_meanDatasets 27484/0
       (2024-02-25T04:54:44Z) - 28886/0 (2024-03-31T04:52:16Z): mean
       2006128285.083195, previous mean 1800447875.596608 (stddev
       141900852.558272), relative change 11.42%

   Please [3]check it out and provide an explanatory description.
   change detection variable Horreum Alerting

   --
   You received this message because you are subscribed to the Google
   Groups "rhtap-perf-notify" group.
   To unsubscribe from this group and stop receiving emails from it, send
   an email to [4]rhtap-perf-notify+unsubscribe@redhat.com.
   To view this discussion on the web visit
   [5]https://groups.google.com/a/redhat.com/d/msgid/rhtap-perf-notify/msg
   .1711863184120.vertxmail.458%40e70fecd3fb22.

References

   1. https://horreum.corp.redhat.com:8443/test/254
   2. https://horreum.corp.redhat.com:8443/run/28328#dataset0
   3. https://horreum.corp.redhat.com:8443/changes?test=load-tests-result&fingerprint={"machineName":"load-test-ci-daily-10u-10t-redhat-appstudio-load-test"}
   4. mailto:rhtap-perf-notify+unsubscribe@redhat.com
   5. https://groups.google.com/a/redhat.com/d/msgid/rhtap-perf-notify/msg.1711863184120.vertxmail.458@e70fecd3fb22?utm_medium=email&utm_source=footer
```

But looks like link `https://horreum.corp.redhat.com:8443/changes?test=load-tests-result&fingerprint={"machineName":"load-test-ci-daily-10u-10t-redhat-appstudio-load-test"}` does not work for me. Looking at developer console, network tab, that request returns "400 Bad Request".

If I copy&paste a working URL from the browser, port is missing and fingerprint parameter data are encoded: `https://horreum.corp.redhat.com/changes?test=load-tests-result&fingerprint=%7B%22machineName%22%3A%22load-test-ci-daily-10u-10t-redhat-appstudio-load-test%22%7D`.

**To Reproduce**

1. Login to Horreum in one tab
2. Open the link above marked as "[3]"

**Version**

Current version in Prod.

firefox-124.0.1-2.fc39.x86_64

**Comment by whitingjr** [comment]
@jhutar thanks for creating this issue , I can reproduce this issue locally. A fix will be coming soon.

**Comment by whitingjr** [comment]
The email provided has url links in a Reference section at the end. These links were stripped out the email and put into a Reference section by Google Groups.
 When Horreum created the email there was no Reference section. As we can see [here](https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/templates/change_notification_email.html#L1-L11).
 Checking in Horreum code [EmailPlugin.notifyChanges](https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/notification/EmailPlugin.java#L80)   the code is encoding the fingerprints parameter before adding to the template.

 What this indicates is that as the email is passing through Google Groups it is getting processed. Then finally the message is being dumped by neomutt to html.

 I can't tell which system is to blame. Google Groups or Neomutt.
 A system is rendering the body of the email to be displayed in the browser but not re-encoding the fingerprints parameter in the References section added by Google Groups.

 I am not a member of the google groups `RHTAP-Perf-Notification` so unable to verify what's rendered on Google Groups link [3] has the fingerprint parameter encoded correctly.
@jhutar Can you verify that and provide feedback to eliminate one culprit ?

**Comment by jhutar** [comment]
Hello and thanks for looking into this! In:

https://groups.google.com/a/redhat.com/g/rhtap-perf-notify/c/9ocLgycONR8

there is:

```
<a href="https://horreum.corp.redhat.com:8443/changes?test=load-tests-result&amp;fingerprint=%7B%22machineName%22%3A%22load-test-ci-daily-10u-10t-redhat-appstudio-load-test%22%7D" target="_blank" rel="nofollow" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=https://horreum.corp.redhat.com:8443/changes?test%3Dload-tests-result%26fingerprint%3D%257B%2522machineName%2522%253A%2522load-test-ci-daily-10u-10t-redhat-appstudio-load-test%2522%257D&amp;source=gmail&amp;ust=1713466047069000&amp;usg=AOvVaw10OoW101FAruXLbEOWSCw2">check it out</a>
```

So I guess you are right. Sorry for the confusion.

**Comment by whitingjr** [comment]
Hi, are you happy for this issue to be closed ?

**Comment by whitingjr** [comment]
@jhutar ^^

**Comment by jhutar** [comment]
Yep, please let's close this as it might be problem with mine setup. Sorry for that!
