### ISSUE TITLE
GH-1577 / Make processNewOrUpdatedSchema asynchronous

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Horreum#1579]
Short term fix for of https://github.com/Hyperfoil/Horreum/issues/1577

**Feature idea.**

Since fixing https://github.com/Hyperfoil/Horreum/issues/1577 in the proper way could require some additional refactoring, that could have other implication, as short-term goal we decided to make the `processNewOrUpdatedSchema` https://github.com/Hyperfoil/Horreum/blob/3849f043bb457deb86df5fb8ecab5fc8fc3de588/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java#L176-L182
asynchronous, such that the creation/update of a `Schema` would become quite immediate and the `run_schemas` update (especially the `FIND_RUNS_WITH_URI` query execution) is handled asynchronously.

**Describe the solution you'd like**

Create a new channel to manage this new event type, on event receiving, trigger the `processNewOrUpdatedSchema` method.

**Additional information**

n/a

**Comment by lampajr** [comment]
Worth to note that with this (temporary) approach we should stick with an increased transaction timeout (~120s) otherwise the `FIND_RUNS_WITH_URI` query will go in timeout even in the async process.

**Comment by willr3** [comment]
This approach should also include some update to the UI so that the user knows the change is being processed in the background. There are parts of UI (e.g. assigning a run's schema) that relied on this being a synchronous operation.

**Comment by lampajr** [comment]
> This approach should also include some update to the UI so that the user knows the change is being processed in the background. There are parts of UI (e.g. assigning a run's schema) that relied on this being a synchronous operation.

Good point, since this is meant to be (hopefully) a temporary solution, do you think it would be enough to show a popup/warning/alert on schema save?

**Comment by willr3** [comment]
Something in the banner display or any other inline popup might work. I would avoid any use of `alert` or a modal.
