### ISSUE TITLE
TestServiceImpl.getByNameOrId() should return HTTP 404 Not Found if test is not defined

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#158]
Currently the method returns `null` if there is no test, with a HTTP 204: Content response.  If the test is not found, it should return a HTTP 404 response

**Comment by rvansa** [comment]
Correct; this method is currently not used in the UI so it slipped through. Do you think it's useful to accept both names and IDs or should I let the implementation match the meaning in API path `/api/test/byName/<name>`?
