### ISSUE TITLE
Unable to update Schema access

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Horreum#1592]
**Describe the bug**

Unable to change the Schema access using the "Change Access" functionality [1], every request fail with 500 internal server error with message: `Access change failed (missing permissions?) Cannot invoke "org.hibernate.metamodel.mapping.JdbcMapping.getJdbcValueBinder()" because "jdbcMapping" is null` [2].

In fact the issue is that the access is wronly mapped to the database, it is passed as `string` but the db accepts `int` https://github.com/Hyperfoil/Horreum/blob/cfcafb5e4fbfe6a4da48bf49c37e98da1f2979eb/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java#L285

[1] 
![image](https://github.com/Hyperfoil/Horreum/assets/26715795/5aca6a7a-cbe4-4308-a214-3939ed5e9928)

[2] 
![image](https://github.com/Hyperfoil/Horreum/assets/26715795/42d0eb24-4e4e-4df9-ad57-441ca36d229d)

**To Reproduce**

1. On `Schemas` page, click on the three dot button on the right of a specific schema
2. Click "Change access"
3. Set a different access and click update
4. You will see the error reported above

**Version**

What is the version of Horreum ?

Version `0.12.1` as well as the `master` branch (ref. 9e5c2f4d0f3c2a83c44ab62e3ad789b4532bf7ea).

**Comment by lampajr** [comment]
A possible solution is to change line https://github.com/Hyperfoil/Horreum/blob/cfcafb5e4fbfe6a4da48bf49c37e98da1f2979eb/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java#L285

with something like:
```java
query.setParameter(2, access.ordinal()); 
```

this way the string will be converted to the corresponding ordinal/numeric value

**Comment by stalep** [comment]
Hm... I believe this regression crept in as part of the effort of us trying to standardize on enum values being strings in the client API....
Internally we should keep encoding enums as ints imo.

**Comment by lampajr** [comment]
> Hm... I believe this regression crept in as part of the effort of us trying to standardize on enum values being strings in the client API.... Internally we should keep encoding enums as ints imo.

From a model perspective the mapping is fine, the problem is that for `updateAccess` functionality we are using a native query.. therefore the mapping should be done manually.

I fixed that using the Hibernate model update + persist.

**Comment by willr3** [comment]
>  Internally we should keep encoding enums as ints imo.
We use entity attributes in native sql throughout Horreum. If we are going to standardize on integer encoding for enums then we should probably replace the static references to ordinal numbers in all sql to ensure the sql is not susceptible to silent errors if the ordinals change.
