### ISSUE TITLE
Go to changes link is broken

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Horreum#1639]
**Describe the bug**

From the `Changes detection` tab, if you click on `Go to changes` button it will redirect to the old `/changes?test=...` url which is not working anymore.

**To Reproduce**

Open change detection tab and client `Go to changes`:

![image](https://github.com/Hyperfoil/Horreum/assets/26715795/6827a338-453d-4827-a980-d4cb16237944)

Then you should see:

![image](https://github.com/Hyperfoil/Horreum/assets/26715795/0caaf589-cc1e-4619-ae9b-517b7bac2212)

**Version**

What is the version of Horreum ?

From `main` branch

```
$ git rev-parse HEAD

a3ed1b101bb8e0de9ac7cdf390dd6391ed02e2a6
```

**Comment by lampajr** [comment]
Given that the `changes` page has been moved under the corresponding `Test` (as a tab), we cannot simply redirect the location to `/test/<testId>#changes` as this won't work because the tabs selection is managed internally by `FragmentTabs` component and there is no way (at the moment) to programmatically change the selected tab from outside of the `FragmentTabs` itself.

_On the other hand I don't even think we still need this "Go to changes" button because, at the moment, both pages reside in the same Test page._ 

So, I'd propose to _**completely get rid of**_ the "Go to changes" button as users can simply select the "Changes" tab from that page, wdyt @johnaohara ?

**Comment by johnaohara** [comment]
@lampajr One of the main ideas behind the re-org of the UI was to remove the need for these "Go To" buttons that were in a lot of places of the UI, so I am +100 to remove it!
