### ISSUE TITLE
Compare function failed

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1678]
**Describe the bug**

When opening some tests, the following errors are displayed in the UI:

![image](https://github.com/Hyperfoil/Horreum/assets/959822/f406aea7-eb5e-42e4-b4b6-7a11bb6e1161)

**Comment by lampajr** [comment]
Could it be the same as https://github.com/Hyperfoil/Horreum/issues/1567 ?

**Comment by johnaohara** [comment]
Ah yes, missed that. CLosing as duplicate of #1567
