### ISSUE TITLE
`RoleManager.setRoles()` called multiple times during a transaction

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1726]
**Describe the bug**

`RoleManager.setRoles()` is a very expensive operation, which requires a full round trip to the DB every time it is called to define the roles for the curren connection. `@WithRoles` is used liberally within the codebase, and is often called multiple times within the same transaction.

This unnecessary frequent calling adds an overhead to processing new datapoints

For this following upload, `setRoles()` utilized 35.62% of cpu time

![Screenshot from 2024-05-22 06-20-21](https://github.com/Hyperfoil/Horreum/assets/959822/97bf8dd7-1afe-4ba8-b81c-69d43bd446fd)

**Comment by barreiro** [comment]
#1257 and a relaxed security policy would improve this massively.

Sort term, the reset of roles could happen only when closing the connection and not after each intercepted call.
