### ISSUE TITLE
Switching between change detection variables the UI not updating to current Model name.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#1730]
**Describe the bug**

Switching between variables reveals the UI is not updating correctly.
Still displays "Fixed Threshold" when the Condition is now "Relative difference of means (1)"

![muddled-model-in-ui](https://github.com/Hyperfoil/Horreum/assets/708428/62011ba7-41f9-4469-a27f-0abee09be378)

**To Reproduce**

Create multiple change detection variables. each with different implementations.
switch between variables.

**Version**

What is the version of Horreum ?

If you are using a development branch; what is the commit id ?

```
0.13.0
```

**Comment by johnaohara** [comment]
@whitingjr is this a duplicate of: https://github.com/Hyperfoil/Horreum/issues/1123 ?

**Comment by whitingjr** [comment]
yes duplicate
