### ISSUE TITLE
"Recalculate datasets" modal does not retrive test data

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1734]
**Describe the bug**

From the list of Tests, clicking on "Recalculate Datasets" from the "Action Menu"

![image](https://github.com/Hyperfoil/Horreum/assets/959822/367400d1-f752-431b-be10-58de39494165)

Displays a modal without the relevant data;

![image](https://github.com/Hyperfoil/Horreum/assets/959822/195ca081-ae70-4bbf-8d23-81642fa3cf35)

**Comment by lampajr** [comment]
This fix has been included as part of https://github.com/Hyperfoil/Horreum/pull/2084
