### ISSUE TITLE
return an error indication for invalid /labelValues filter parameters

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Horreum#1780]
Right now an invalid filter to `<test>/labelValues` returns the full list of labelValues as though `filter` was not used. This can lead to users incorrectly believing the results reflect the desired filter.

I beleive we should instead return an error to indicate that the provided filter was invalid. This will lead to correct filter usage rather than silently accepting invalid filters.

**Comment by lampajr** [comment]
If I am not wrong, this change was incorporated into https://github.com/Hyperfoil/Horreum/pull/1977, therefore I am closing this one as completed.

Feel free to re-open it if I misunerstood something.
