### ISSUE TITLE
Add tests for Servlet Filter objects.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#182]
The following Servlet spec components exist in the project. In anticipation of the porting task #116  add some tests to detect if functionality is the same after the port.

- RouteFilter
- UserTeamsFilter
- ~GrafanaUserFilter~ Grafana disabled in testsuite

**Comment by johnaohara** [comment]
DYK if there a reason for grafana being disabled in the testsuite? iirc the testsuite should spin up an emulated env in containers (including grafana) and test against that env.  It would be good if we could get coverage of that filter as well

**Comment by rvansa** [comment]
@johnaohara It is disabled in the tests that don't interact with it. We should add tests that spin it up and test the interactions, too, but there's no reason to spend CPU cycles starting it and dropping it in other tests.

**Comment by johnaohara** [comment]
@rvansa +1 I think we should have some tests that verify that integration

**Comment by whitingjr** [comment]
Seeing there isn't any reason not to I'll add some tests.
