### ISSUE TITLE
Can not add dependency to horreum-api without horreum-backend

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#184]
`horreum-backend` module contains JSON Jackson converters used for enitites in `horreum-api`

Users wishing to write an application to register as a webhook need to add a dependency on both `horreum-api` and `horreum-backend` modules to be able to use entities defined in `horreum-api` as objects in their webhook application.

e.g. for `io.hyperfoil.tools.horreum.entity.json.Run` the data is marshalled by;

```
   @NotNull
   @Type(type = "io.hyperfoil.tools.horreum.entity.converter.JsonUserType")
   public JsonNode data;
```
`io.hyperfoil.tools.horreum.entity.converter.JsonUserType` is currently in `horreum-backend`

**Comment by rvansa** [comment]
I wouldn't expect that users would use them as **entities**, just as Jackson-annotated POJOs. In fact `horreum-client` happily consumes just `horreum-api`, not backend (it excludes the ORM-related dependencies). But I agree that if the consumer brings in Hibernate this could cause some trouble, and the split package causes some warnings (I am going to fix those by shuffling stuff around a bit).
