### ISSUE TITLE
Problematic use of @Entities as DTO's in REST API

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#186]
I am opening this issue to start a discussion about @Subject.  

Currently the `horreum-api` module exposes JPA `@Entity` as DTO objects used in the REST API.  While this is convenient from a code maintenance perspective, this causes a number of issues for users of the `horreum-api` module;

1. For frameworks that automatically augment JPA `@Entity` with hibernate specific bytecode (e.g. Quarkus), DTO objects are serialized to include the hibernate internal fields that are used to track entity state within an application. These additional serialized fields are not relevant to consumers of the REST API.
2. As the `horreum-api` module depends on Hibernate, explicit exclusions need to be placed in any projects that depend on `horreum-api` but **does not** depend on Hibernate. Otherwise `quarkus-hibernate-orm-panache` and `quarkus-hibernate-validator` (and all of their transitive dependencies) are pulled into an application that depends on `horreum-api`
3. Any application that **does** depends on `horreum-api` and Hibernate will automatically have all of the Horreum JPA entities registered in the meta-model for that application. e.g this can cause all of the Horreum tables to be created in any Hibernate application with the following property enabled `hibernate.hbm2ddl.auto=drop-and-create` (or equivalent)

The ideal solution is to decouple the JPA Entities from DTO's returned by the REST API and maintain the JPA Entites within `horreum-backend`

**Comment by rvansa** [comment]
I didn't realize the augumentation gets serialized, too. So far I considered sufficient to exclude hibernate-related jars (annotations that don't have a matching class on classpath are simply ignored), but you're right that if the application gets that from other place it can still cause trouble.

I am still reluctant to keep two objects and manually copy properties from one to another. Therefore I'd suggest to move the entities to `hibernate-backend`, and create the contents of `hibernate-api` programmatically stripping JPA-related annotations from that module. Do you think this would work?

**Comment by johnaohara** [comment]
It could work. You would need to generate the `hibernate-api` DTO objects (annotation stripped Entities) before you could compile `horreum-backend` module. and we would need to ensure that the REST api was using the DTO classes, not the entity classes.  

Would you leave the jackson annotations on the `@Entity` classes? removing JPA/Hibernate annotations could be easily automated, adding annotations would be more tricky

**Comment by rvansa** [comment]
No, I would create `hibernate-api` (to be consumed by `hibernate-client` and others) only *after* backend. Backend would *not* consume `hibernate-api`, it would use the unstriped entities. 

Regarding jackson - yes, I would keep those annotations in. We'll make the choice for the users (jackson vs. jsonb) - or is there any other reason why you're asking?

**Comment by johnaohara** [comment]
If `horreum-backend` used the unstripped entities, that wouldn't solve issue no. 1 - serializing the hidden hibernate fields.

**Comment by johnaohara** [comment]
`Regarding jackson - yes, I would keep those annotations in. We'll make the choice for the users (jackson vs. jsonb) - or is there any other reason why you're asking?`

The reason for asking was I was assuming that the REST api would be using the stripped entities and we would need to ensure that any jackson annotations either remained, or were added if they were not kept on the entity classes

**Comment by johnaohara** [comment]
@rvansa Sanne pointed me towards this, looks interesting: https://www.jpa-buddy.com/

https://www.youtube.com/watch?v=MKQRRWqNLNk

**Comment by rvansa** [comment]
Hi @johnaohara , I've added 7fa729bb0f5886da8b6d4749ff40ddda1e310699 which gives you JPA-free `horreum-api` module - could you test that out?
