### ISSUE TITLE
AlertingServiceTest.testMissingRules() Test case is failing in CI

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#191]
This test fails consistently in CI, but passes when run locally. At present, all PR CI builds are failing due to this test

**Comment by rvansa** [comment]
Thanks for reporting, I've noticed that though it works for me locally. I have that on my TODO list.

**Comment by rvansa** [comment]
Fixed in 48f98f6a05a8f2e331d1b4d22f833ea832a5c3cf
