### ISSUE TITLE
Missing Horreum default user in dev mode

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Horreum#1927]
**Describe the bug**

Horreum started up in development mode does not have the default `user` anymore.

Am I missing something?

**To Reproduce**

Start Horreum:
```bash
mvn -Dquarkus.test.continuous-testing=disabled quarkus:dev -pl 'horreum-backend'
```

Then open http://localhost:8080 and try to login using the default account.

I tried:
- `user/secret` which was the previous default
- `horreum.bootstrap/secret` just a try

Moreover in the logs I don't see the dummy password creation:
```bash
>>>
>>> Created temporary account horreum.bootstrap with password 4gGK8hcutXvbAF4p
>>>
```

**Notes**

I might be wrong but it looks like this has been introduced with https://github.com/Hyperfoil/Horreum/pull/1900, I tried to revert that and I was able to see again:
```bash
>>>
>>> Created temporary account horreum.bootstrap with password 4gGK8hcutXvbAF4p
>>>
```

**Version**

What is the version of Horreum ?

`master`

If you are using a development branch; what is the commit id ?

```
$ git rev-parse HEAD
2851657fa2b260123be0138a2818f109958c1199
```

**Comment by lampajr** [comment]
I think the root cause is because in `dev` mode the `horreum.keycloak.realm` and `dev.quarkus.keycloak.admin-client.realm` are not equal:
- `%dev.quarkus.keycloak.admin-client.realm=master`
- `horreum.keycloak.realm=horreum`

And the `SecurityBootstrap` is using the first one, i.e., checks in the master realm https://github.com/Hyperfoil/Horreum/blob/2851657fa2b260123be0138a2818f109958c1199/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java#L33

@barreiro you might have more context on this :pray:

**Comment by barreiro** [comment]
@lampajr thanks. I know what's going on, but I have not been able to fix it completely,
