### ISSUE TITLE
suspected issue in Access enum

### ISSUE THREAD

**Issue by vitorz** [Hyperfoil/Horreum#202]
Hello, using api like POST **_api/run/data_** i know the expected type for **_access_** parameter is a string (**PUBLIC**, **PRIVATE**, **PROTECTED**). But if you look at the automatically generated **api definition yaml file**, you can see the access parameter is defined as an **integer enum**. Because this, also the automatically generated clients are wrong. In my opinion the problem is that  swagger for query parameters use jackson annotation to decide which type to assign, but **vertx** don't use the same logic. A possible solution could be changing the **_serialize_** method in the **_Access_** enum type in this way:
```
@JsonValue
public String serialize() {
      return name();
}
```
but i don't know all the code base, so i'm not able to understand the impact of this change in the whole project.

**Comment by rvansa** [comment]
Hi, thanks for the issue. You're right that docs suggest that you should use a string value like `PUBLIC` while the openapi spec requires `0`, `1` or `2`, with definition:
```
components:
  schemas:
    Access:
      enum:
      - 0
      - 1
      - 2
      type: string
```
Changing that to enum name would need multiple changes in the UI, so I would rather not do that. I thought that Horreum actually supports both numbers and names in the input but when I've checked the RESTEasy lookup won't find it with numeric value, the asymmetry between input and output is certainly not right. I'll see how can I hint RESTEasy to accept numbers, too.

**Comment by rvansa** [comment]
Okay, so the `@JsonCreator` wasn't static, and maybe needed to be called `fromString` for RESTEasy. Now should both numeric and textual representation work.
