### ISSUE TITLE
Update the documentation with migration guide from Horreum token to the API token

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#2154]
> Overall looks good to me but I'd update the documentation accordingly, i.e., removing any mention to the Horreum token like https://horreum.hyperfoil.io/docs/tasks/upload-run/#getting-horreum-token and adding a new migration guide (even very simple) clearly stating out to migrate from Horreum token to the API token approach.

_Originally posted by @lampajr in https://github.com/Hyperfoil/Horreum/pull/2100#pullrequestreview-2381917486_

**Comment by barreiro** [comment]
Created a `Migration Guides` section in https://github.com/Hyperfoil/Horreum/wiki
