### ISSUE TITLE
Unable to get 'Get Started' to work

### ISSUE THREAD

**Issue by danp11** [Hyperfoil/Horreum#2192]
Hi, 

Im trying to start Horreum via 
curl -s https://raw.githubusercontent.com/Hyperfoil/Horreum/0.6/infra/start.sh | bash
as outlined here: https://horreum.hyperfoil.io/docs/tutorials/get-started/

Im running via docker compose and the containers starts except from 
Error: No such object: **horreum_app-init_1**
Waiting for app-init container to complete...

When looking at the end of the log for app_init it says: 

+ echo 'Horreum initialization complete'
2024-11-28T11:05:31.383183428Z {"errorMessage":"Role with name dev-team already exists"}{"errorMessage":"Role with name dev-viewer already exists"}{"errorMessage":"Role with name dev-uploader already exists"}{"errorMessage":"Role with name dev-tester already exists"}{"errorMessage":"Role with name dev-manager already exists"}{"errorMessage":"User exists with same username"}Horreum initialization complete 

Any ideas? Thanks in advance.

Regards
Dan

**Comment by lampajr** [comment]
Hi @danp11, thanks for trying Horreum!!

That specific getting started guide is pretty outdatated as it is still referencing Horreum `0.6` and we are now at version `0.16.x`. I will try to collect some more up to date instructions/guides and get back to you asap (I am afk right now), sorry for this inconvenience!

**Comment by lampajr** [comment]
Hey again 👋🏻 

Unfortunately we don't have docker-compose like setup anymore as we moved all the infrastructure setup in the `infra-common` [module](https://github.com/Hyperfoil/Horreum/tree/master/infra). What I would recommend to get started with Horreum is to start it up in `dev` mode:

**Prerequisites**

Having installed the following tools/libs:
- Docker
- Java
- Maven

**Start Horreum**

Clone the respository and checkout the tag/branch you want to try:

```bash
git clone https://github.com/Hyperfoil/Horreum.git
cd Horreum
git checkout <tag/branch>
```

Build the project

```bash
mvn clean install -DskipTests -DskipITs
```

Start it up:

```bash
mvn quarkus:dev -pl horreum-backend
```

And then you can login using `horreum.bootstrap` / `secret` credentials

Ref. https://github.com/Hyperfoil/Horreum?tab=readme-ov-file#getting-started-with-development-server

**Comment by danp11** [comment]
Ok! and appreciate your quick reponse. 

I will try to start in the dev mode as you suggest. 

/Dan
