### ISSUE TITLE
No warning displayed for datasets with elements without $schema

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#240]
The schema Labels UI provides the ability to try json paths on test runs. Currently the "Try it!" feature is not displaying relevant test datasets.

![execute-json-paths-02](https://user-images.githubusercontent.com/708428/183433152-ac4a250a-186b-4801-a063-1c17e812465d.png)

**Comment by rvansa** [comment]
When a Transformer does not use neither the `Target schema URI` field  nor combination function we might end up with Dataset with some non-annotated data. There is a warning about "No schema" but we should display more concrete errors, and during transformation, too.
