### ISSUE TITLE
 New schema save fails

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#25]
Saving a newly defined schema fails with the following constraint violations, even though the failed fields are supplied;

```
javax.validation.ConstraintViolationException: Validation failed for classes [io.hyperfoil.tools.repo.entity.json.Schema] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=owner, rootBeanClass=class io.hyperfoil.tools.repo.entity.json.Schema, messageTemplate='{javax.validation.constraints.NotNull.message}'}
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=access, rootBeanClass=class io.hyperfoil.tools.repo.entity.json.Schema, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
```

Http Request:

```
POST /api/schema HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Content-Length: 168
Accept: application/json
Sec-Fetch-Dest: empty
Authorization: Bearer {BEARER_TOKEN}
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Content-Type: application/json
Origin: http://localhost:8080
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:8080/schema/_new
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7
Cookie: G_AUTHUSER_H=0
```

Payload:

```
{"name":"quarkus-quickstart","uri":"http://quarkus.io/startup-schema/0.1","description":"Quarkus quickstart schema","schema":false,"access":"PUBLIC","owner":"dev-team"}
```

The schema defined in the `JSON Schema` text area is also not sent in the payload to `POST /api/schema`

**Comment by johnaohara** [comment]
{BEARER_TOKEN} is a correct token, I just omitted it from the output

**Comment by rvansa** [comment]
Are you sure you're running latest version 59a2b27e5fe182a349bb9134dfe40a24333d2eb0 ? I've just tried to create a new schema in scalelab and it worked without issues.

**Comment by johnaohara** [comment]
Yes, I am running;

```
commit 59a2b27e5fe182a349bb9134dfe40a24333d2eb0 (HEAD -> master, origin/master, origin/HEAD)
Author: Radim Vansa <rvansa@redhat.com>
Date:   Wed Apr 29 11:46:39 2020 +0200
```

**Comment by rvansa** [comment]
Okay, I can reproduce with this request (not from UI), investigating...

**Comment by rvansa** [comment]
It seems this is a bug in `org.eclipse.yasson` when deserializing `false` into custom object; the parser mistakenly jumps one level down in the object and therefore your JSON is interpretted as
```json
{
   name: ...,
   uri: ...,
   description: ...,
   schema: {
      owner: ...,
      access: ...,
   }
}
```

**Comment by rvansa** [comment]
I've filed https://github.com/quarkusio/quarkus/issues/9111

Have did you get the `schema: false` in the UI? I get that when I explicitly change the contents of the text area to `false`, but if I wipe it out completely it sends `null`.

**Comment by johnaohara** [comment]
The contents of the text area was a json schema, will try with an empty schema and see what happens

**Comment by rvansa** [comment]
Closing here as it doesn't seem to be fixable in Horreum/yaup at this moment. Please reopen if you figure out when does UI pass `false` for schema.
