### ISSUE TITLE
Recalculation takes longer than expected from the UI

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#277]
The progress bar shown in the UI currently displays the progress of recalculating datapoints, however when this finishes not all changes are detected yet.

* [ ] Reflect this in the UI - the dataset should be fully processed only when we've checked if there's any change. This can be a bit difficult as we trigger recalculation for the 'next' datapoints as well...
* [ ] While we'll be adding some indices to DB soon the queries might not be optimal and this prolongs the process.
* [x] #280
* [ ] Make sure that during recalculations like this we're not doing O(n^2) analyses - let's have a test for that?

**Comment by johnaohara** [comment]
Recalculation architecture was modified in https://github.com/Hyperfoil/Horreum/pull/705
