### ISSUE TITLE
Improve documentation for running standalone

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#29]
When running Horreum on bare metal or in docker, the Keycloak realm for Horreum needs to be updated; 

Horreum-ui client needs the following updating;

 - Root URL
 - Valid Redirect URIs
 - Admin URL
 - Web Origins

The documentation needs updating to reflect this

**Comment by rvansa** [comment]
https://horreum.hyperfoil.io/docs/baremetal.html
