### ISSUE TITLE
Upgrade node.js

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#299]
Upgrade node.js to a later version

**Comment by shivam-sharma7** [comment]
hey @jesperpedersen   this mean `npm install` or something else

**Comment by shivam-sharma7** [comment]
what do you think about this issue now? should we open a PR?

**Comment by jesperpedersen** [comment]
Please, work with @johnaohara on this, as he started a branch.

We should aim for nodejs 18.15.0 and friends for the next round; before moving to nodejs 19.x
