### ISSUE TITLE
long test and fingerprint makes it impossible to reach date picker on changes page

### ISSUE THREAD

**Issue by jhutar** [Hyperfoil/Horreum#309]
Hello! Long test and fingerprint makes it impossible to reach date picker on changes page:

![image](https://user-images.githubusercontent.com/3397250/203820048-4ad0b8ff-d0f3-4eab-b1de-9d77e2ed6a76.png)

A workaround is to remove a fingerprint, change the date and put fingerprint back.

I'm on firefox-106.0.1-1.fc36.x86_64 if it makes any difference.

**Comment by jesperpedersen** [comment]
Hi @jhutar - Would you be able to supply a patch for this ?

**Comment by rvansa** [comment]
I've applied the fix in aed89a622b7fd6eb9aad832f103a8d9cac05e329, thanks!
