### ISSUE TITLE
picking "all" timeframe on changes page squeezes all my data to far to the right

### ISSUE THREAD

**Issue by jhutar** [Hyperfoil/Horreum#310]
Hello! Picking "all" timeframe on changes page squeezes all my data to far to the right. I would expect the graphs will be trimmed just to data width.

![image](https://user-images.githubusercontent.com/3397250/203821106-a8364651-9d8a-488c-b8f4-eeff88cd4e76.png)

I'm on firefox-106.0.4-1.fc36.x86_64

**Comment by jesperpedersen** [comment]
Hi @jhutar - Would you be able to supply a patch for this ?

**Comment by jhutar** [comment]
Hello @jesperpedersen. I do not plan to work on it.

I assume effort for this change is above what I'm willing to invest. It might change if I'm asked to work on it, but given what I know (and more importantly what I do not know), if I would be asked to work on it, I would not consider it responsible use of my time (it is completely different stack).

**Comment by jesperpedersen** [comment]
Can you describe the precise steps that you take ? And, if you have some sample data to show this that would be great.

**Comment by rvansa** [comment]
@jesperpedersen One example would be https://horreum.corp.redhat.com/changes?test=Quarkus%20-%20getting-started%20-%20JVM&timespan=2000000000

**Comment by rvansa** [comment]
Implemented a fix in 9c3c61ac67086a1de5f897084bb33d3deb5172ef
