### ISSUE TITLE
sorting changes on .../changes page by "Time" does not seem to work

### ISSUE THREAD

**Issue by jhutar** [Hyperfoil/Horreum#311]
Hello! Looks like sorting by time does not work:

![image](https://user-images.githubusercontent.com/3397250/203822940-ada0659a-4b43-4d70-b420-19a6e1ae8604.png)

vs:

![image](https://user-images.githubusercontent.com/3397250/203823002-3cabfcc5-debf-46bd-b297-fcb2cc4111f3.png)

I'm on firefox-106.0.4-1.fc36.x86_64

**Comment by jhutar** [comment]
Hello @jesperpedersen. I do not plan to work on it.

I assume effort for this change is above what I'm willing to invest. It might change if I'm asked to work on it, but given what I know (and more importantly what I do not know), if I would be asked to work on it, I would not consider it responsible use of my time (it is completely different stack).

**Comment by rvansa** [comment]
Fixed in b800cf6a569e5a182ab61fa17938d3342d70c785
