### ISSUE TITLE
Publish OpenAPI specs

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#313]
During build we generate the OpenAPI spec in `horreum-model/target/generated/openapi.yaml` but we should publish that on the website, too, ideally in a browse-able form. Existing documentation in Java code should be converted into annotations that will be reflected in the OpenAPI, too.

**Comment by johnaohara** [comment]
@rvansa this reminded me there is an issue with the generated openapi schema: #315

**Comment by johnaohara** [comment]
@rvansa how does this get updated when the api changes?

**Comment by rvansa** [comment]
Only manually, these are different repos. Theoretically we could have a Github Action that would issue a PR to docs, but that sounds pretty complicated.
Instead I would rather make the manual update a part of the release process, the same as we do with Hyperfoil auto-generated docs.
