### ISSUE TITLE
Deleting runs

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#32]
I am still split on whether we should add the option to delete a run. On one hand we want to keep what we had and prevent accidental removal (like with git history), on the other hand I often have a run that crashed or was cancelled and pollutes the run history.

Should we add an option to trash it which just won't display it (flagging the database row(s)) and extra option to display trashed runs, too? Trashed runs won't pollute UI and probably won't affect load times, but these will still occupy the DB. Maybe an admin-only option to delete everything trashed older than X months?

WDY'all think?

**Comment by jesperpedersen** [comment]
Having a user level option to "trash" a run would be good. And, the admin can actually deletes those.

**Comment by johnaohara** [comment]
+1 to trash a run and not delete the data immediately

**Comment by rvansa** [comment]
Implemented in 58ebe107da3947b81e33d6d9d3e9f99aca480fe2
