### ISSUE TITLE
Fingerprint labels fields are empty on Changes page when you access it by a link

### ISSUE THREAD

**Issue by dupliaka** [Hyperfoil/Horreum#325]
**Describe the bug**

Horreum notifications provides a link to the changes  when it gets detected. 
Here is the outcomes if go by this link:

1) If you have empty cash  you will get the graph with empty fingerprints.
2) Otherwise it will not show the graph and you will see  empty fingerprints fields.
3) When I try to confirm the change it shows me 
{
  "details": "Error id 56a06059-0012-4436-88ac-2bbd6150e0b4-56",
  "stack": ""
}

**To Reproduce**

1) Create a test with multiple datasets with Change detection for multiple fingerprint labels
2) Open it in Changes and copy link to the page
3) Open the link in a new tab

**Version**

What is the version of Horreum ?
0.7-SNAPSHOT

Commit Id : a71b0ad12d5d31416e54351a2576168050b6ecf8

**Comment by rvansa** [comment]
Fixed in 0ba4e5e09635e7b82660a2c77ae775fc6d8df34f
