### ISSUE TITLE
Updating descriptions

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#33]
While the run data itself should be immutable, sometimes I forget to add a description to the run (configuration parameters for the SUT) and it would be nice to update it afterwards. However the description is just one JSONPath-fetched piece of data from the immutable run data.

I think that setting up a generic way to update certain piece of the data is excessive. I would rather:
1. Add a description column to the Run itself
2. Add an optional jsonpath field to Schema that will allow to fetch the Run data
3. Add a column to all run views that will display this description, an option to edit it

That way the original description stays the same but you could overwrite it. The downside is that this won't be propagated to anyone who fetches the data using `/api/run/123456/data` but I don't think it's a big issue.

**Comment by jesperpedersen** [comment]
Updating a description could be useful, and it could be another field.

There could be an endpoint `/api/run/123456/description` that would fetch all description fields for a run.

**Comment by rvansa** [comment]
There's already `/api/run/123456` which returns you the `Run` object (that includes test id, ownership etc...) and that would give you the description AND the data. It's just that e.g. Hyperfoil reporter handles data from Hyperfoil, not Horreum.
