### ISSUE TITLE
Plan for Upgrade to Quarkus 3.0

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#333]
Quarkus 3.0.0.Alpha2 has already been released, with planned release of "3.0.0.Final in February 2023"

The ML thread is here: https://groups.google.com/g/quarkus-dev/c/xjHIBk6Mx7k

There are some major breaking changes that Quarkus 3.0 will bring, the Quarkus team have produced a migration guide for extension maintainers, but should be useful for us as well: https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x

We should plan to test against early 3.0 release to see what breaks, however ORM6 is not included in the Alpha release so far

**Comment by rvansa** [comment]
I am a bit worried about the Jakarta stuff. The api and client modules are Java 8 and we rely on the `javax.ws.rs` annotations. We could keep the old package names in api through `horreum-api-generator` that's already rewriting the bytecode but that part will require some work.
Alternatively we could say bye bye to old Jenkins versions, require at least [2.361.1](https://www.jenkins.io/blog/2022/06/28/require-java-11/) and base API on a version that's not a fossil...

**Comment by jesperpedersen** [comment]
This is a task like upgrading to React 5

**Comment by johnaohara** [comment]
I'll pick up this task. The migration path is non-trivial, even with the Quarkus 3.0 migration tool. 

There are a lot of API changes in ORM6 that means this is not a straightforward upgrade

**Comment by jesperpedersen** [comment]
@johnaohara We don't need this right now, but feel free to assign

**Comment by stalep** [comment]
I made an attempt, but it's not straight forward as there are many (breaking) changes...
- Hib6 supports JSON now and they have a JSON Jackson mapper afaik. We use a lot of `.addScalar("filterlabels", JsonNodeBinaryType.INSTANCE)`, I changed that to .TEXT as I could not find any  JSON mapper in org.hibernate.types.StandardBasicTypes.
- ScrollableResults have changed, but it's fairly easy to rewrite to the new API
- Hib6 also defaults to some different types, eg Enums are now tinyints, there are also some changes to timestamp default types. These can be overwritten though with the @JdbcTypeCode annotation.
- Hib6 has also changed how they generate sequence tables. I'm not sure of the implications it has with "normal" tables in Horreum as we have fairly "standard" sequences, but where it does break is for ActionLogDAO as it has a mapped superclass PersistenceLog.
When starting Quarkus it fails with this message: `org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing sequence [ActionLog_SEQ]`
I tried to set this property in application.properties: `hibernate.id.db_structure_naming_strategy=legacy` but it still fails.
https://github.com/stalep/repo/commit/1b2192ac6060765f13a3bc9803b1b88d847af464

**Comment by johnaohara** [comment]
I have broken my machine and don't have access to an IDE atm, but one immediate thought

> I made an attempt, but it's not straight forward as there are many (breaking) changes...
> 
>     * Hib6 supports JSON now and they have a JSON Jackson mapper afaik. We use a lot of `.addScalar("filterlabels", JsonNodeBinaryType.INSTANCE)`, I changed that to .TEXT as I could not find any  JSON mapper in org.hibernate.types.StandardBasicTypes.

I don't think this will work, were are using the jsonb datatype throughout the DB schema

**Comment by stalep** [comment]
> I don't think this will work, were are using the jsonb datatype throughout the DB schema
Yes, I also have concerns about that, but I could not find any examples for this in hib6, not any solutions at vladm.. either. I'll search some more.

**Comment by jesperpedersen** [comment]
This is a complex issue - that will require porting in all layers.

Starting with #518 will likely help, as we can let Hibernate do the DB layout, and just install our custom functions.

**Comment by stalep** [comment]
Closing as we're on Quarkus3 in master
