### ISSUE TITLE
Managed @Entity used in REST API

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#343]
**Describe the bug**

The REST API is still marshalling `@Entity` objects when endpoints are called. 

An `API` module was introduced in https://github.com/Hyperfoil/Horreum/commit/7fa729bb0f5886da8b6d4749ff40ddda1e310699 to fix https://github.com/Hyperfoil/Horreum/issues/186, however the REST API is still deserializing REST API json params to ORM Entities.  

This causes issues in the services where unmanaged Entities are `merged`, but as the entities are unmanaged, their state is not correctly maintained.

In part, this caused: https://github.com/Hyperfoil/Horreum/issues/340

**Comment by jesperpedersen** [comment]
We will only fix this on the master branch

**Comment by stalep** [comment]
Completed
