### ISSUE TITLE
Integration tests are flakey - Consider disabling flakey tests until they can be fixed

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#361]
**Describe the bug**

The integration tests often fail in tests that are unrelated to changes in PRs. Atm it is difficult to determine if a change has introduced a regression or not. I suggest that we disable the flaky tests until they can be stabilized so that we can be sure that PR's do not introduce any regressions

**Comment by jesperpedersen** [comment]
I have done this under a wrong issue ref :(
