### ISSUE TITLE
AllTests.tsx: Pagination

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#387]
Add pagination to the AllTests.tsx file

**Comment by shivam-sharma7** [comment]
@johnaohara if you have time then collab with me to solve this-https://github.com/shivam-sharma7/Horreum/commit/2428e0aeb9ec51f0282ae36eb7ab7aeac4b731b9

**Comment by johnaohara** [comment]
@shivam-sharma7 do you want to open a draft PR and we can collaborate there?

**Comment by shivam-sharma7** [comment]
@johnaohara See- #621
