### ISSUE TITLE
Can not run tests from Intellij

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#397]
**Describe the bug**

Attempting to run tests in Intellij fails with the following error;

```
/working/projects/redHat/Hyperfoil/Horreum/horreum-client/src/main/java/io/hyperfoil/tools/RunServiceExtension.java:85:193
java: package org.jboss.resteasy.reactive.multipart does not exist
```
cause by: https://github.com/Hyperfoil/Horreum/blob/master/horreum-client/src/main/java/io/hyperfoil/tools/RunServiceExtension.java#L23

I had a workaround for this issue previously, but we need to resolve so a fresh import into intelij works correctly

**Comment by stalep** [comment]
This works in master
