### ISSUE TITLE
failed to compute cache key: "/keycloak-horreum.json"

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#416]
### Discussed in https://github.com/Hyperfoil/Horreum/discussions/414

<div type='discussions-op-text'>

<sup>Originally posted by **shivam-sharma7** March 13, 2023</sup>
I got this error during set up this project locally I run following  docker command.

`docker-compose -p horreum -f infra/docker-compose.yml up -d`

quay.io/keycloak/keycloak:20.0.1@sha256:8830f76112b62231f17b43f115a3deca4de7e4a33eeee298e85cb295c5810e8a                                      0.0s 

 => ERROR [2/4] COPY keycloak-horreum.json /opt/keycloak/data/import/                                                                                        0.0s

------
 > [2/4] COPY keycloak-horreum.json /opt/keycloak/data/import/:
------

failed to compute cache key: "/keycloak-horreum.json" not found: not found
ERROR: Service 'keycloak' failed to build : Build failed</div>

**Comment by jesperpedersen** [comment]
Thanks
