### ISSUE TITLE
App.tsx replace `Switch `  with  `Routes`

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#421]

**Comment by rukundob451** [comment]
Hello @shivam-sharma7, is this issue still available?

**Comment by shivam-sharma7** [comment]
yes

**Comment by rukundob451** [comment]
@shivam-sharma7, kindly need some more context to this issue?

**Comment by johnaohara** [comment]
@shivam-sharma7 this issue looks like a duplicate of https://github.com/Hyperfoil/Horreum/issues/419?
