### ISSUE TITLE
husky bad variable name

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#423]
### Discussed in https://github.com/Hyperfoil/Horreum/discussions/422

<div type='discussions-op-text'>

<sup>Originally posted by **shivam-sharma7** March 15, 2023</sup>
# During commit i got error
```
git commit -m "update routes"

```
.husky/pre-commit: 5: export: sharma/Desktop/Open-Source/Horreum/webapp/node/node:/usr/lib/git-core:/home/shivamsharma/.nvm/versions/node/v18.13.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python311/Scripts/:/mnt/c/Python311/:/mnt/c/Program: bad variable name
husky - pre-commit hook exited with code 2 (error)</div>

**Comment by johnaohara** [comment]
@shivam-sharma7 what environment was this running in? is there a space in the path where the project is built from?

**Comment by shivam-sharma7** [comment]
I am using windows 11 but I was running project in ubuntu wsl environment.
