### ISSUE TITLE
 TestRuns.tsx: Combine "Owner" and "Access" columns

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#428]

**Comment by shivam-sharma7** [comment]
Only need to combine both?

**Comment by jesperpedersen** [comment]
Yes, it is the same for all these issues,

```
| Owner             |
| MyAccount <padlock> |
```

**Comment by shivam-sharma7** [comment]
Please you fix one then i will get idea and i will fix all related.because you know i am still not able to see UI
