### ISSUE TITLE
TestDatasets.tsx: Combine "Owner" and "Access" columns

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#430]

**Comment by rukundob451** [comment]
Hello @jesperpedersen, I was actually trying to work on this but was failing to run the react web app 
![horreumWEBAPP](https://user-images.githubusercontent.com/67878128/236767819-8c4e7261-6c61-4532-818a-9b408976a771.png)

**Comment by jesperpedersen** [comment]
You need to follow

https://github.com/Hyperfoil/Horreum/blob/master/doc/Windows.md
https://github.com/Hyperfoil/Horreum/blob/master/README.md

**Comment by rukundob451** [comment]
> You need to follow
> 
> https://github.com/Hyperfoil/Horreum/blob/master/doc/Windows.md https://github.com/Hyperfoil/Horreum/blob/master/README.md

Thank you @jesperpedersen, checking them out and getting to work on them.
