### ISSUE TITLE
Document how to configure Horreum intgration with Grafana

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#490]
Create documentation that covers how to;
- Configure Horreum as a datasource in grafana
- Create Grafana queries for Horreum to allow creation of custom grafana visualizations

**Comment by jesperpedersen** [comment]
Its due to https://github.com/Hyperfoil/Horreum/commit/d1f2d94c77228ee119a546ae689d460ca2617e43

Setup Grafana, and then document the process of integration.

Feel to discuss in a forum thread though...

**Comment by rukundob451** [comment]
Alright @jesperpedersen discuss in the forum thread as suggested thank you for the suggestion.
