### ISSUE TITLE
Replace Quinoa link in README.md

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#501]
`replace this link- [Quinoa](https://github.com/quarkiverse/quarkus-quinoa)`
`replace with this- [Quinoa](https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/)`

**Comment by shivam-sharma7** [comment]
@jesperpedersen assigned

**Comment by rukundob451** [comment]
@shivam-sharma7 can I work on this?

**Comment by jesperpedersen** [comment]
Yes

**Comment by shivam-sharma7** [comment]
@rukundob451 Go

**Comment by rukundob451** [comment]
> @rukundob451 Go

I am done with it @shivam-sharma7.
