### ISSUE TITLE
Unable remove invalid schema

### ISSUE THREAD

**Issue by dupliaka** [Hyperfoil/Horreum#53]
Cannot remove schema with invalid URI 

Internal Server error
{
  "details": "Error invoking subclass methodError id 7e370d55-57cd-4254-9429-aae1c81ef4ec-9",
  "stack": ""
}

Steps to reproduce:

1. Go to Login -> Schemas -> New Schema
2. Fill in URI "test"
3. Press "Save"
4. Press ...
5. Press "Delete" x2

**Comment by rvansa** [comment]
Thanks, I'll take a look. Deleting non-existent schema should give a better error message. URI `test` is not 'invalid' for Horreum, it just matches string without trying to parse it in any way.

**Comment by rvansa** [comment]
Fixed in d2854f24ffa27319d122621ee0ce929e64d11ff4 , thanks for spotting this.
