### ISSUE TITLE
Drop test, start and end selectors from schema

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#56]
We offer too many choices to select the timestamps and while these are optional in the schema it's likely that users can just add them to the upload query anyway.

Let's do the upload in an opinionated way, requiring the parameters and dropping these from the schema.

@johnaohara @willr3 Thoughts?

**Comment by johnaohara** [comment]
If we register an application via a webhook and that application receives a notification about a new run, how would that downstream application be able to obtain the start/end timestamps for that run?  Is that data included in the Notification?

**Comment by rvansa** [comment]
Webhooks receive the Run JSON, that has already the timestamps extracted. I don't see much relevance here.

**Comment by johnaohara** [comment]
After our separate conversation I realise that this is a different issue of schema definition rather removing the use of selectors. I would vote for dropping selectors in schema and making the UX simpler.

**Comment by rvansa** [comment]
Implemented.
