### ISSUE TITLE
Json Schema code editor shows null after adding extractor

### ISSUE THREAD

**Issue by dupliaka** [Hyperfoil/Horreum#57]
Steps to reproduce:
1. Go to Schemas
2. Create new Scema
3. Type testSchemaName in name field
4. Type {"$id":"testID"} at code editor and press upload button -> the URI name should become testID
5. Press Save
6. Go to testSchemaName -> SchemaExtractors -> Add Extractor add extractor with accessor testExtractor and Json path .data
7. Press Save
8. Go to testSchemaName schema

Expected code editor contains  {"$id":"testID"}
Actual: code editor contains  null

**Comment by rvansa** [comment]
Fixed in 424ca9fc90071134478cc8b91c95dbd53278963c , thanks for reporting.
