### ISSUE TITLE
Move  Example configuration

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#588]
move- https://github.com/Hyperfoil/Horreum#example-configuration
after- https://github.com/Hyperfoil/Horreum#getting-started-with-development-server

**Comment by shivam-sharma7** [comment]
#603

**Comment by johnaohara** [comment]
Is this related to #603? if so, please comment on that PR and close this issue, we should handle changes in the open PR

**Comment by shivam-sharma7** [comment]
> Is this related to #603? if so, please comment on that PR and close this issue, we should handle changes in the open PR

yeah, I have seen you have done this in you current PR.

**Comment by shivam-sharma7** [comment]
@johnaohara sorry but we need to do that so see https://github.com/Hyperfoil/Horreum/issues/588#issue-1790816966

**Comment by shivam-sharma7** [comment]
You can simply change README so CI will not run
