### ISSUE TITLE
Drop ability to create a new test during run upload

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#59]
When a new run to a non-existing test is uploaded, the test is create automatically. `uploader` role should be sufficient for creating a new test.

**Comment by johnaohara** [comment]
Can we make this explicit to opt in/out?  

For example I uploaded some results recently and the url encoding was incorrect for the test name.  This would have resulted in a new test being created, and the response code would have been correct so from an automation perspective this would have appeared to be successful. Luckily, creating the new test failed.

If Horreum implicitly creates a new test if it can not find an existing test, then we could get ourselves in a position where we need to clean up data in horreum

**Comment by rvansa** [comment]
@johnaohara That makes sense. So, should it be opt-out (to preserve current behaviour, and make the first upload easy, however most likely not solving your problem by default), or opt-in (IMO when you think about adding that option you can already create the test manually)?

**Comment by johnaohara** [comment]
IMO it should be opt-in and disabled by default. it could be a param that is passed to the rest api e.g. `createNewTest=y` / `createTestIfMissing=y`?

**Comment by rvansa** [comment]
OK, so you'd prefer to drop the current behaviour.

Is it really worth to have this option at all?

**Comment by johnaohara** [comment]
I think the current behaviour could easily lead to a situation where users have multiple tests for essentially the same dataset, esp if users are not using the gui. I think we should try and avoid this behaviour by default. 

wrt to creating new tests, I have always explicitly created new jobs before uploading data so I can set the visibility, ownership etc.

**Comment by rvansa** [comment]
The ability to create a new test when uploading a run has been removed.
