### ISSUE TITLE
Syntax error for JSON input

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#595]
```
ERROR:  syntax error at or near "[" of jsonpath input
STATEMENT:  SELECT jsonb_agg(v)#>>'{}' FROM (SELECT jsonb_path_query(jsonb_path_query(data, '$[*] ? (@."$schema" == $schema)', ('{"schema":"' || $1 || '"}')::jsonb), $2::jsonpath) AS v FROM dataset WHERE id = $3) AS values 
```

**Comment by stalep** [comment]
Do you have any steps of reproducing this? From grepping it's a query in DatasetServiceImpl.queryData.

**Comment by whitingjr** [comment]
This could be user input that is causing this query not to be syntactically correct. The parameter `$2` supplies a jsonpath.
Can this issue still be reproduced ?

**Comment by stalep** [comment]
Closing for now, no steps to reproduce
