### ISSUE TITLE
Usability: Runs tab search query behaviour.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#60]
When using a remote Horreum server I am seeing odd behaviour using the search field. Currently the search criteria is updated as data is entered. Very reactive.
 In practice for me there is a delay before the update comes to the client. That causes every second character to be missed. eg

expected:HelloWorld
actual: Hlool

 An alternative can be the field only search after a button is clicked.

**Comment by rvansa** [comment]
Fixed in 1e60c9d168c385069614a51bc523f33a5e17b3a7, thanks for reporting.
