### ISSUE TITLE
Local dev mode blocked by CORS

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#602]
Local dev mode is blocked by some browsers when trying to impersonate other users in keycloak.

1. Start local dev env with a database containing a number of users and results
2. log into keycloak as an administrator
3. select a user, and chose to impersonate that user
4. open the local dev env page (http://localhost:8080)

You should be using horreum as if you are the user you chose to impersonate, however in some browsers (ff) access to resources is denied by a CORS policy

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8180/realms/horreum/account. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 401.
```

![cors_impersonate](https://github.com/Hyperfoil/Horreum/assets/959822/b7a5e162-9b17-4b85-983c-77ce8cbe7ab3)

**Comment by whitingjr** [comment]
This can no longer be recreated. Solved probably by this hosting all resources on the same origin server.
