### ISSUE TITLE
Remove isDebugEnabled wrapper.

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#624]
Find all isDebugEnabled and remove the wrapper.

So
```java
            if (LOG.isDebugEnabled()) {
                LOG.debugf("Something");
            }
```

Should just be:

```java
 LOG.debugf("sometjing");
 ```

The `debugf` part of the code internally already has the `isEnabled logic in it.

**Comment by shivam-sharma7** [comment]
@jesperpedersen WDYT?

**Comment by jesperpedersen** [comment]
I'm ok with this
