### ISSUE TITLE
Usability issue: Labels and a Transformer on a Schema do not co-exist.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#630]
**Describe the bug**

Any label values become unavailable/deleted when a Transformer is added to a Schema.

**To Reproduce**

Create a Label on a Schema. Check the value is created.
Create a Transformer on the same Schema. This causes the label values to disappear.

**Version**

 0.7.11

**Comment by stalep** [comment]
I added some more tests with this issue in mind to the Quarkus3 migration pr: https://github.com/Hyperfoil/Horreum/pull/626/commits/a0fd8f541fd0abd6201586a7550bdb46dd292f83
I could not reproduce this issue through the unit test, but we should check after the Quarkus3 pr is merged with master.

**Comment by stalep** [comment]
@whitingjr can you reproduce this with master now?

**Comment by whitingjr** [comment]
@stalep Yes it can be reproduced.
 Beforehand the default Dataset is relied on to produce Label values for a Schema.
 When a Transformer is added to the Schema then that default Dataset no longer is available. Only the Datasets generated by the Transformer(s).

**Comment by stalep** [comment]
If a label is added/changed/deleted all datasets will be recalculated, but transformes should not afaik. Can you check against master?

**Comment by whitingjr** [comment]
still still occurs. unlikely to be solved.
