### ISSUE TITLE
HTTP 500: When querying via `/api/run/list`

### ISSUE THREAD

**Issue by jhutar** [Hyperfoil/Horreum#631]
**Describe the bug**

When qerying via `/api/run/list`, for some queries I get 500 ISE.

**To Reproduce**

```
$ curl -v -G -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" "https://horreum.example.com/api/run/list" --data-urlencode "limit=10" --data-urlencode "page=1" --data-urlencode "query=$.*"
[...]
< HTTP/1.1 500 Internal Server Error
[...]
```

**Version**

Current Red Hat internal instance. About Horreum dialogue says: 0.7.11

**Comment by stalep** [comment]
I have a branch that's based on the quarkus3 migration pr where I try to reproduce the issue, but it works.. ref: https://github.com/stalep/repo/tree/issue_631

**Comment by jhutar** [comment]
Hello all! Would you have some estimate on when this fix can land on Prod instance?

**Comment by johnaohara** [comment]
@jhutar I will take a look at how to fix in the 0.7x branch

**Comment by jesperpedersen** [comment]
Do we have a reproducer ?

**Comment by johnaohara** [comment]
@jesperpedersen , @stalep created a test in the quarkus3 PR branch, it needs to be backported to master/0.7.x

**Comment by johnaohara** [comment]
we are able to reproduce manually

**Comment by stalep** [comment]
[RunServiceTest.testListAllRunsFromFiles ](https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java#L654) uses a similar query to the one in this issue and it works. I do not think it's worth backporting as I hope we can push master to prod in the not too distant future.

**Comment by stalep** [comment]
@jhutar do you mind testing this query against Horreum now? I hope we have solved it in the version we have in prod

**Comment by stalep** [comment]
I've verified locally against the prod db that this is resolved

**Comment by jhutar** [comment]
Sorry for late reply. Yes it works, thank you!
