### ISSUE TITLE
Relative Difference of Mean not detecting large change

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#633]
A change detection variable defined with the following relative difference of means

<img width="1230" alt="Screenshot 2023-09-12 at 16 20 20" src="https://github.com/Hyperfoil/Horreum/assets/959822/0b3178d1-4f7b-49a1-95e2-fa5a366b08bc">

is not detecting large changes after the first 2 changes have been detected;

<img width="1230" alt="Screenshot 2023-09-12 at 16 21 27" src="https://github.com/Hyperfoil/Horreum/assets/959822/1ceeaf14-c512-48cd-8799-224148448e2e">

**Comment by johnaohara** [comment]
the reason it was not fired was due to the number of proceeding datapoints in the configuration is set to 5.  The relative difference of means requires 5 data points from the last change point. so in this case the large changes were not analysed as there were not enough datapoints from the previous change.

**Comment by jhutar** [comment]
Hello John. What would be a fix here? Given our specific data, would you have a recommendation on change detection config?

**Comment by johnaohara** [comment]
@jhutar if your case, you can reduce the "Minimal Number of preceeding datapoints" to 1, although I would keep the threshold quite high to stop noisy alerts. 

I think we need to improve the docs on threshold configuration and the implications
