### ISSUE TITLE
Label extractor aggregation function not exposing value. 

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#639]
**Describe the bug**

An aggregation function such as .reduce(a,b) is not producing a value.

**To Reproduce**

Create a Label with an extractor for a series of values. Add a javascript function to reduce a series of values to a single scalar.
Recalculate datasets for the the run/test.
Then go check the values in a Dataset using the "Show Label Values" button. The value is empty.

**Version**

```
0.7.11
```

**Java**

What is the version of Java ?

```
11
```

**Comment by whitingjr** [comment]
It seems the [aggregation function](https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java#L71) in the SQL is producing an ArrayNode with a single element. `["[2,4,6,8,10]"]`  Rather than 5 elements expected.
Reduce function to produce an average value can be achieved. With the following example function
```value => { return value[0].slice(1,-1).split(',').reduce((a,b) => Number.parseInt(a)+Number.parseInt(b)) / value[0].slice(1,-1).split(',').length; }```

**Comment by willr3** [comment]
I don't understand why Extractors behave differently depending on the result of the extractor. I do not think the result value should change how Combination Functions or Rendering Functions need to handle the data. Is there a reason the SQL needs to wrap the result into an array?

**Comment by whitingjr** [comment]
My example was misleading. My testcase was adding sample data incorrectly. The most recent commit adds sample data correctly. However, this does not change the fact the resulting JsonNode produced uses an ArrayNode to wrap the result. The most recent commit now flattens the hierarchy by removing 1 ArrayNode from the JsonNode object. The JS function can work as expected.
