### ISSUE TITLE
Cannot change Max difference for last datapoint

### ISSUE THREAD

**Issue by dupliaka** [Hyperfoil/Horreum#65]
**Max difference for last datapoint** parameter of regression variable resets to 0 if I try to change it to another value.

Steps to reproduce

1. Create a new test my-new-test
2. Add a regression variable to it
3. Go to "Show advanced settings" and change "Max difference for last datapoint " to 0.3
4. Press save and recalculate
5. Go back to Test tab
6. Reopen my-new-test 
Expected "Max difference for last datapoint " is 0.3
Actual "Max difference for last datapoint " is 0

**Comment by rvansa** [comment]
Fixed in 0d5c79968e476d9b783743684b182d31b66f12cb, thanks for reporting.
