### ISSUE TITLE
Missing data Notification Rule name is not mandatory

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#653]
The rule "Name" field for Missing data notifications is not mandatory

![image](https://github.com/Hyperfoil/Horreum/assets/959822/b24af40d-bab7-4f07-b246-12ba42bb2ab5)

This is inconsistent with other forms

**Comment by stalep** [comment]
Hm, so NotificationSettings.name is annoted with  `@JsonProperty( required = true )`
According to this: https://stackoverflow.com/questions/45867473/should-you-use-notnull-and-jsonpropertyrequired-in-the-same-object 
 It will not do any validation. So we either need to continue to use Bean Validation with `@NotNull` or Swagger with `@ApiModelProperty`

**Comment by stalep** [comment]
I assume there are more fields like this we do not validate any longer...

**Comment by johnaohara** [comment]
> Hm, so NotificationSettings.name is annoted with `@JsonProperty( required = true )` According to this: https://stackoverflow.com/questions/45867473/should-you-use-notnull-and-jsonpropertyrequired-in-the-same-object It will not do any validation. So we either need to continue to use Bean Validation with `@NotNull` or Swagger with `@ApiModelProperty`

`@JsonProperty( required = true )` just means it should be in the json object when it is deserialized/serialized, nothing about its value
