### ISSUE TITLE
Schema export content not JSON for master branch 0.8-SNAPSHOT.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#672]
**Describe the bug**

Schema export produces file not containing JSON. Instead the content is `[object Object]`.

**To Reproduce**

1 Create a new Schema, name: dummy, urn:dummy:0.1
2 Export schema to file system
3 inspect the contents of exported file

**Version**

```
423bde26bffd98542de7c49b485476461cd8cbb5
```

**Java**

```
17
```

**OS**

F38

**Browser**

FF117

**Comment by stalep** [comment]
Hm, so we have a test for that endpoint:
https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java#L213
We also push back the output of that call back to Horreum to make sure the json is correct. I verified that the output from that test is valid.
Do you mind checking if there is something wrong on the ui side?

**Comment by whitingjr** [comment]
You are right. This is a problem of the browser saving the file. The raw response from Horreum contains JSON.
