### ISSUE TITLE
Run: Request failed

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#712]
* Boot in dev mode
* Load example data
* Navigate to http://localhost:8080/run/1#run

```
ERROR
The request failed and the interceptors did not return an alternative response
FetchError@http://localhost:8080/static/js/bundle.js:51937:5
./src/generated/runtime.ts/BaseAPI/this.fetchApi@http://localhost:8080/static/js/bundle.js:51803:19
```

**Comment by johnaohara** [comment]
I am seeing this

![image](https://github.com/Hyperfoil/Horreum/assets/959822/09ca8f40-5287-4001-94ae-b028b8e6ddf0)

@jesperpedersen  is that what you see as well?

This is caused by unhandled marshalling of String -> JSON in typescript
