### ISSUE TITLE
Export: UI error

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#713]
* Boot in dev mode
* Load example data
* Login as `user`
* http://localhost:8080/test/11#export

```
ERROR
true
handleError@http://localhost:8080/static/js/bundle.js:189807:58
./node_modules/webpack-dev-server/client/overlay.js/createOverlay/<@http://localhost:8080/static/js/bundle.js:189830:18
```

**Comment by johnaohara** [comment]
@jesperpedersen where do you see this error? do you have a screenshot?

**Comment by johnaohara** [comment]
i see an error caused by: https://github.com/Hyperfoil/Horreum/issues/709

but that is handled in the error notification

**Comment by jesperpedersen** [comment]
Can't reproduce anymore
