### ISSUE TITLE
 ReactDOM.render is no longer supported in React 18, need to migrate to createRoot

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#717]
A Warning is reported in the developer console of the browser:

`Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`

![image](https://github.com/Hyperfoil/Horreum/assets/959822/177fa48b-2831-4d9e-96df-105c2808636a)

**Comment by jesperpedersen** [comment]
The login functionality needs work

**Comment by shivam-sharma7** [comment]
Thanks for this fix, PR was ready but due to some collage stuff, was not able to submit.
