### ISSUE TITLE
Label array only contains initial value.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#724]
**Describe the bug**

The extractor for a label is seen to contain only the initial value. Rather than all values.
Can be seen here

/schema/173#labels

**To Reproduce**

Create a Label that works on an array of data. Check the Combination function. The first value is displayed.

**Version**

0.7.11

**Java**

```
17
```

**OS**

any

**Browser**

FF118

**Comment by whitingjr** [comment]
This issue has been fixed.

**Comment by johnaohara** [comment]
@whitingjr do we know which PR fixed this issue?
