### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#743]
We should provide documentation of our OpenAPI API - both in the repository and website

**Comment by jesperpedersen** [comment]
https://davidgarcia.dev/posts/openapi-to-markdown/

**Comment by johnaohara** [comment]
We now have: https://horreum.hyperfoil.io/docs/reference/api-reference/

This can be populated with the openapi yaml/json during the release process

There is an issue with navigation atm, i will fix that

**Comment by johnaohara** [comment]
I think we need to look at descriptions on the API that are used to autogenerate the reference to provide more context for the api reference

**Comment by johnaohara** [comment]
The site is using https://redocly.com/  it dynamically renders the api based on a yaml definition. I am working on making it render better in the site

**Comment by johnaohara** [comment]
The api is now fully documented: https://horreum.hyperfoil.io/openapi/
