### ISSUE TITLE
Importing test with transformer from another instance fails

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#761]
Useres trying to import a Test from another Horreum instance fails if the Test has transformers defined

```
2023-10-17 14:20:49,970 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-15) SQL Error: 0, SQLState: 23503
2023-10-17 14:20:49,971 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-15) ERROR: insert or update on table "test_transformers" violates foreign key constraint "fk_transformer_id"
  Detail: Key is not present in table "transformer".
```

**Comment by stalep** [comment]
As Transformers are tied to Schemas we must assume that if we import a test from another instance, then the transformers on test most likely have different ids and schematIds vs the new instance. We can try to find an existing transformer using the name and schemaName, but if that fails we can't really connect transformers in an import.

**Comment by johnaohara** [comment]
From a user perspective, this is a failure and is not clear how to resolve. So we need to handle this situation better, either with a better error message, or ignore the transformer with a warning

**Comment by stalep** [comment]
Ok, so if we can't find a matching Transformer we will ignore it.

**Comment by jesperpedersen** [comment]
We should `WARN` log enough information to know which precise Test(s) we are talking about.

Then we can check the logs and see how big the problem is...
