### ISSUE TITLE
Limit accessor names

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Horreum#77]
JDBC has a limit on column lenght; when we use accessors as column names the name could be truncated.

Therefore we should warn users that these long accessors are not going to work.

**Comment by jesperpedersen** [comment]
?

https://www.baeldung.com/jpa-size-length-column-differences

**Comment by johnaohara** [comment]
@jesperpedersen I am assuming this relates to identifier length, which i think is 63 bytes by default?

https://www.postgresql.org/docs/13/limits.html

**Comment by rvansa** [comment]
Solved.
