### ISSUE TITLE
Remove hashing WithRoles - configure TLS encryption between application and database

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#779]
Replace custom encryption for roles with TLS encryption between application and database

We need to;

- [ ] remove hashing code in application
- [ ] remove hashing code in DB `has_role` procedure
- [ ] remove `horreum.db.secret` property
- [ ] remove `dbsecret` database table
- [ ] allow enable ssl in dev/test mode
- [ ] update documentation on how to define a secure connection between Horreum and production database

**Comment by johnaohara** [comment]
For dev mode we could do something similar to for the database connection: https://github.com/Hyperfoil/Horreum/pull/746

**Comment by jesperpedersen** [comment]
We currently depend on [pgacrypto](https://www.postgresql.org/docs/current/pgcrypto.html) for this
