### ISSUE TITLE
Document Functions in Labels, combination functions etc

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#795]
Document;

- [ ] what functions are,
- [ ] how functions are calculated 
- [ ] Provide examples
- [ ] #803

**Comment by whitingjr** [comment]
@johnaohara there is some documentation already on [Labels with Functions](https://github.com/Hyperfoil/Horreum/blob/master/docs/site/content/en/docs/Tasks/define-schema-and-views/index.md?plain=1#L34-L36). Does that provide enough information for the "how functions are calculated" task above ?

**Comment by johnaohara** [comment]
There are a number of issues. 

Labels and combination functions are some of the core functionality for Horreum, and we have 1 sentence buried in a document about Schemas.

If you put yourself in the position of a user who does not know Horreum very well, how do they find this information, and when they do, what are the parameters for combination functions etc, how do they debug etc?

We need to make labels and functions more prominent, make it clear that they are a core function, and provides examples details of what users can/can't do and how to debug when they fail

**Comment by whitingjr** [comment]
ok, I have already started creating content that provides guidance on troubleshooting and where to find the dialogues.
It is good to know I should rework what you have already created.
