### ISSUE TITLE
Document Filters/Queries in API

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#796]
There are a number of API endpoints that allow users to filter results based on a Filter/Query. 

These are executed against the JSON documents or Label values to return a filtered set of resources.

We need documentation on how these function, where they can be applied, including examples

**Comment by whitingjr** [comment]
What's the scope here. Does this include both JSONPath query and SQL statement parameters ?

**Comment by whitingjr** [comment]
@johnaohara ^^

**Comment by johnaohara** [comment]
Fixed by https://github.com/Hyperfoil/Horreum/pull/1544
