### ISSUE TITLE
`SchemaService.dropToken()` should not return a String value and is incorrect HTTP verb

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#800]
`SchemaService.dropToken()` should be a `@DELETE` operation and should not return a value

**Comment by jesperpedersen** [comment]
Should we consider `RunService` as well ?

**Comment by johnaohara** [comment]
probably, am reviewing the API atm, am just working through `RunService` ;)

**Comment by jesperpedersen** [comment]
I think the same applies for `resetToken`...
