### ISSUE TITLE
Investigate flaky test in CI

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#806]
`io.hyperfoil.tools.horreum.svc.DatasetServiceTest.testSchemaAfterData` sometimes fails in CI, we should investigate why this tests fails;

https://github.com/Hyperfoil/Horreum/actions/runs/6625372984/job/17996226595#step:7:2545

**Comment by jesperpedersen** [comment]
We have `-Dci-test=true` as well
