### ISSUE TITLE
Review use of @DyanmicUpdate, deprecated since Hibernate 6.0 

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#811]
We are using `@DynamicUpdate` to control updates to `RunDAO`: https://github.com/Hyperfoil/Horreum/blob/f66f0c9eb69f6b1e4e927cd4871e685fdcd3cff8/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/RunDAO.java#L27

This annotation has been deprecated since ORM 6.0 and the behaviour of the system may now be different since the removal of large parts of the messagebus

The use of this annotation should be reviewed

**Comment by shivam-sharma7** [comment]
we can use `@EntityListeners`?
