### ISSUE TITLE
change detection calculation functions not working and not saving

### ISSUE THREAD

**Issue by dustinblack** [Hyperfoil/Horreum#822]
**Describe the bug**

In change detection I'm setting a variable using two labels, both of which are floating points. I'm trying to simply multiply them to understand how to write the function, but everything I try ends up with it telling me that it "Cannot turn {"Kernel Average ms":258.12,"Kernel Standard Deviation %":7.973} into a floating-point value for variable Testing/TEST Kernel Average ms". I just have the variable defined with those two labels: "Kernel Average ms" and "Kernel Standard Deviation %", and for testing I have tried the calculation:

`(input)=>input["Kernel Average ms"] * input["Kernel Standard Deviation %"]`

![image](https://github.com/Hyperfoil/Horreum/assets/10656942/1f3a8219-f955-4f33-a2ac-1c595a4b446a)

Running the recalculation with this function results in the error noted above reported in the logs. Then in the changes view, the chart for this variable is blank. Going back to the edit view, the calculation function I had added is completely gone.

![image](https://github.com/Hyperfoil/Horreum/assets/10656942/589edd53-5c63-4a6a-ad2a-4bdbdea9f7c8)
![image](https://github.com/Hyperfoil/Horreum/assets/10656942/2f47330c-5fb9-485d-88d9-b1411c577e0f)

I tried this again with a much simpler test, having only one floating point label in the variable and setting the calculation function to simply `value => value * 2`, and in this case I don't get any error logs on recalculating, but the change graph does not reflect values with the multiplier (only the base value of the label), and when I go back to edit the variable again for the change detection, the calculation function is always gone.

![image](https://github.com/Hyperfoil/Horreum/assets/10656942/a170448f-9d86-4a14-bc96-dcc17f8cdca4)

**Version**
Horreum (hosted) 0.9.4

**Browser**
Brave v1.59.117
(FWIW I did try with Brave "shields down" and had the same results)

**Comment by whitingjr** [comment]
@johnaohara  I am still seeing this issue in 0.9.5 release.

**Comment by johnaohara** [comment]
@whitingjr i see, the PR has not been back-ported to 0.9.x branch

**Comment by johnaohara** [comment]
Backport PR: https://github.com/Hyperfoil/Horreum/pull/869

**Comment by whitingjr** [comment]
@johnaohara  Tested again, this time on 0.9.6 and it is fixed. ty
