### ISSUE TITLE
Regression tolerance comments in series view.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#83]
Add a comment to Regression Series view to indicate points that are outside the configured tolerance.

**Comment by rvansa** [comment]
When you open Series that has a Change, indicated by a red ball in the chart, you can expand a section below the chart that lists all changes. Each change has a pre-filled description and you can use the kebab menu on the right to edit this description.

Is this what you're looking for?

**Comment by whitingjr** [comment]
It is. Thanks.
