### ISSUE TITLE
Update the Jenkins plugin

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#853]
After cutting the 0.10 release, we need to update the Jenkins plugin: https://github.com/jenkinsci/horreum-plugin/

**Comment by johnaohara** [comment]
The existing plugin still works with 0.10.x branch, downgrading severity for now

**Comment by whitingjr** [comment]
This has been completed in https://github.com/jenkinsci/horreum-plugin/pull/18
