### ISSUE TITLE
TestService.importTest will not work if importing as a new Test, export should also be revisited

### ISSUE THREAD

**Issue by stalep** [Hyperfoil/Horreum#860]
The Json structure does not support importing the data if it's importing to a different Horreum instance.
We should look at creating an object structure for both importing and exporting.
This will affect the API so ideally we should try to get it into 0.10...

**Comment by jesperpedersen** [comment]
This is not critical for `0.10.x`

**Comment by stalep** [comment]
In https://github.com/Hyperfoil/Horreum/blob/master/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/Variable.java#L26 we reference Lables as a Json array node with only label names. We should use a list of https://github.com/Hyperfoil/Horreum/blob/master/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Label.java instead.

**Comment by stalep** [comment]
VariableDAO is only referencing Label name as well. Which means we are limited by having global unique label names...
