### ISSUE TITLE
Calculation Function on a Change Detection Variable not getting persisted.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#866]
**Describe the bug**

New Calculation function with the property name `calculation` is not persisted.
The http request to the server does include the Calculation function. See picture of request JSON.
![calculation-function](https://github.com/Hyperfoil/Horreum/assets/708428/8c87862c-2b55-43ba-8c9a-fe76bc123ed8)

In the UI the function can be seen also.
![ui-calculation-function](https://github.com/Hyperfoil/Horreum/assets/708428/244ff3d5-a3fa-4f05-bc40-aa4142185091)

When the UI for the same Test is loaded the new `calculation` property is missing.
![reloaded-test-property-missing](https://github.com/Hyperfoil/Horreum/assets/708428/de79667e-8bb4-401a-bd5d-19b706b60829)

**To Reproduce**

/test/297#vars

**Version**

```
0.9.5
```

**Java**

```
17
```

**Comment by johnaohara** [comment]
@whitingjr is this when you try to define a change detection variable calculation?

Does this look the same issue as: https://github.com/Hyperfoil/Horreum/issues/822 ?

**Comment by whitingjr** [comment]
Yes duplicate.
