### ISSUE TITLE
UI flags errors about Unauthorised requests.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#89]
I am seeing in the Horreum UI a warning popup message.
 This happens after authenticating using Keycloak.

 Keycloak redirects the browser to the index.html page of Horreum. The popup is displayed immediately.

**Comment by whitingjr** [comment]
This happens when the UI tries to load the favicon.ico file. Getting a SC 401 Unauthorised response.

**Comment by rvansa** [comment]
I've seen some failure to fetch favicon in network log, but not in the UI itself. Could you paste a printscreen?
