### ISSUE TITLE
Filters for dataset view are broken

### ISSUE THREAD

**Issue by dustinblack** [Hyperfoil/Horreum#908]
**Describe the bug**

When in the dataset view, when clicking `Show filters` there is only a single drop-down box presented called `values:` and it seems to have a list of objects that should instead be defining the individual drop-downs for each filter.

![image](https://github.com/Hyperfoil/Horreum/assets/10656942/a797d6e4-4881-45a8-82ed-f010e6346e65)
![image](https://github.com/Hyperfoil/Horreum/assets/10656942/49052c4c-2bde-47b7-8e3a-426edd07a75d)

**Version**

Hosted instance: 0.10.1

**OS**

Fedora 39

**Browser**

Brave 1.60.114

**Comment by johnaohara** [comment]
This is the same problem as https://github.com/Hyperfoil/Horreum/issues/867

In the API prior to 0.10.0, the label values were being returned as a Json Object, they are now being returned as a Map
