### ISSUE TITLE
Update Jenkins Plugin - Experiment Profile name check

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#964]
**Feature idea.**

 Update the Jenkins Plugin to provide the ability to check the Experiment Profile name exists for a Test.

**Describe the solution you'd like**

 The ability to check the profile name is valid. Useful when users enter profile name data.
 This check is done before a run starts. The advantage of adding this check is avoiding wasted lab time executing a run that will not match any profile associated with a Test.

**Comment by johnaohara** [comment]
Tracking this in: https://github.com/jenkinsci/horreum-plugin/issues/14
