### ISSUE TITLE
Cannot create a new user

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Horreum#970]
**Describe the bug**
New User creation is failing.

Feel free to attach screenshots as well.
```
2023-12-06 12:28:30,047 ERROR [io.hyp.too.hor.svc.UserServiceImpl] (executor-thread-6832) Failed to create new user org.keycloak.representations.idm.UserRepresentation@4d60ee8d: org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine$3@71392705
```
**Version**

What is the Horreum version ?
```
0.10.5
```
**Java**

What is the version of Java ?

```
openjdk version "17.0.8" 2023-07-18 LTS
```

**PostgreSQL**

What is the version of PostgreSQL ?

```
psql (PostgreSQL) 16.1

```

**OS**

Which Operating System (OS) is used ?

**Browser**

Which is the version of your browser ?

**Tip**

Use \`\`\` before and after the text to keep the output as is.

**Comment by barreiro** [comment]
This is likely cause by conflict in keycloak: either `username` or `email` already exist.

**Comment by johnaohara** [comment]
keycloak admin client 23.0.3 is not compatible with keycloak 17.0.0. If the keycloak server is 23.0.3, the "add user" functionality works as expected
