### ISSUE TITLE
Ensure backend unit tests are resolving postgres image from pom.xml

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#983]
Follow up from: https://github.com/Hyperfoil/Horreum/pull/971

The backend tests currently have a hard-coded postgres image version for unit tests: https://github.com/shivam-sharma7/Horreum/blob/master/horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/PostgresResource.java#L16

the postgres image used for testing should be resolved from the project pom.xml: https://github.com/shivam-sharma7/Horreum/blob/master/pom.xml#L91

The current Integration tests resolve the postgres version from pom.xml and the backend tests should do the same

**Comment by johnaohara** [comment]
@shivam-sharma7 I have opened an issue to track the changes to backend tests using the postgres image defined in the project pom.xml.  You had made a start in #971, please let me know if you are interested in continuing that work

thanks

**Comment by lampajr** [comment]
Closing this as this looks like how it is working at the moment, the postgres version is taken from root pom: https://github.com/Hyperfoil/Horreum/blob/ab6bb187610c2c4762e5cf20d53ba96007221a4a/pom.xml#L95
