### ISSUE TITLE
Migration CRA to VITE

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#995]
Vite is a build tool that aims to provide a faster and leaner development experience for modern web projects.
check-https://vitejs.dev/

**Comment by shivam-sharma7** [comment]
I can start it from new Year 2024!

**Comment by johnaohara** [comment]
What is the purpose of this migration, is it because CRA is no longer maintained? 

@willr3 you mentioned using a deprecated build tool, do you have any thoughts about migrating to vite?

**Comment by shivam-sharma7** [comment]
@johnaohara 

> What is the purpose of this migration, is it because CRA is no longer maintained?
 Yes! and this has very fast build time and its latest and widely used. Thanks

**Comment by shivam-sharma7** [comment]
@johnaohara @stalep WDYT?

**Comment by johnaohara** [comment]
@shivam-sharma7 this looks like the most popular build tool atm, and we need to remove CRA, so +1 for making the switch
